// Functional browser tests: drive the real tools and check outputs. node test/interact.js
const http = require('http'), fs = require('fs'), path = require('path'), assert = require('assert'); const pw = require('/opt/node22/lib/node_modules/playwright');
const M = { '.html': 'text/html', '.css': 'text/css', '.js': 'text/javascript', '.json': 'application/json' };
function serve(dir) { return new Promise((res) => { const s = http.createServer((q, r) => { let p = q.url.split('?')[0]; if (p.endsWith('/')) p += 'index.html'; const f = path.join(dir, p); if (!fs.existsSync(f)) { r.writeHead(404); return r.end(); } r.writeHead(200, { 'content-type': M[path.extname(f)] || 'text/plain' }); fs.createReadStream(f).pipe(r); }); s.listen(0, () => res(s)); }); }
(async () => {
  const b = await pw.chromium.launch(); const dist = path.join(__dirname, '..', 'dist'); let fails = 0;
  const t = async (name, fn) => { try { await fn(); console.log('ok   ' + name); } catch (e) { fails++; console.log('FAIL ' + name + ': ' + e.message.split('\n')[0]); } };
  const sDev = await serve(path.join(dist, 'dev-pocket')), sCalc = await serve(path.join(dist, 'daily-calc'));
  const dev = `http://127.0.0.1:${sDev.address().port}/`, calc = `http://127.0.0.1:${sCalc.address().port}/`;
  const ctx = await b.newContext({ viewport: { width: 1000, height: 900 } }); const page = await ctx.newPage(); const errs = []; page.on('pageerror', (e) => errs.push(e.message));
  await t('json format + error position', async () => { await page.goto(dev + 'json-formatter/'); await page.fill('#in', '{"b":1,"a":[1,2]}'); await page.check('#sort'); await page.click('#fmt'); assert.match(await page.inputValue('#out'), /"a": \[\s+1,\s+2\s+\],\s+"b": 1/); await page.fill('#in', '{"a":1,}'); await page.click('#fmt'); assert.match(await page.textContent('#status'), /Invalid JSON.*line 1/); });
  await t('base64 roundtrip with emoji', async () => { await page.goto(dev + 'base64-encode-decode/'); await page.fill('#in', 'héllo ✓'); await page.waitForTimeout(300); assert.strictEqual(await page.inputValue('#out'), 'aMOpbGxvIOKckw=='); await page.click('#swap'); await page.waitForTimeout(300); assert.strictEqual(await page.inputValue('#out'), 'héllo ✓'); });
  await t('url encode + query parser', async () => { await page.goto(dev + 'url-encode-decode/'); await page.fill('#in', 'a b&c'); await page.click('#enc'); assert.strictEqual(await page.inputValue('#out'), 'a%20b%26c'); await page.fill('#qin', 'https://x.io/?q=dev%20tools&page=2'); await page.waitForTimeout(300); assert.ok((await page.textContent('#query')).includes('dev tools')); });
  await t('uuid generates valid ids', async () => { await page.goto(dev + 'uuid-generator/'); await page.selectOption('#count', '10'); const v = (await page.inputValue('#out')).split('\n'); assert.strictEqual(v.length, 10); assert.ok(v.every((x) => /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(x))); await page.fill('#chk', v[0]); assert.match(await page.textContent('#chkout'), /Valid/); });
  await t('hash sha-256 of abc', async () => { await page.goto(dev + 'hash-generator/'); await page.fill('#in', 'abc'); await page.waitForTimeout(500); assert.ok((await page.textContent('#out')).includes('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad')); });
  await t('timestamp converter', async () => { await page.goto(dev + 'unix-timestamp-converter/'); await page.fill('#in', '1700000000'); await page.waitForTimeout(400); assert.ok((await page.textContent('#res')).includes('2023-11-14T22:13:20.000Z')); });
  await t('regex tester highlights', async () => { await page.goto(dev + 'regex-tester/'); await page.fill('#txt', 'mail bob@site.com and ann@web.com'); await page.waitForTimeout(500); assert.strictEqual(await page.locator('#hl mark').count(), 2); });
  await t('color converter + contrast', async () => { await page.goto(dev + 'color-converter/'); await page.fill('#in', '#ffffff'); await page.waitForTimeout(300); const t = await page.textContent('#res'); assert.ok(t.includes('rgb(255, 255, 255)') && t.includes('1.00:1')); });
  await t('text case + stats', async () => { await page.goto(dev + 'word-counter-case-converter/'); await page.fill('#in', 'hello world foo'); await page.click('[data-case=camel]'); assert.strictEqual(await page.inputValue('#in'), 'helloWorldFoo'); });
  await t('password generator respects options', async () => { await page.goto(dev + 'password-generator/'); await page.uncheck('#symbols'); await page.uncheck('#upper'); await page.uncheck('#digits'); const v = await page.inputValue('#out'); assert.ok(/^[a-z]{16}$/.test(v), v); });
  await t('base converter', async () => { await page.goto(dev + 'number-base-converter/'); await page.fill('#in', 'ff'); await page.selectOption('#from', '16'); await page.waitForTimeout(300); assert.ok((await page.textContent('#res')).includes('11111111')); });
  await t('lorem generator', async () => { await page.goto(dev + 'lorem-ipsum-generator/'); await page.fill('#paras', '2'); await page.click('#gen'); assert.strictEqual((await page.inputValue('#out')).split('\n\n').length, 2); });
  await t('http status filter', async () => { await page.goto(dev + 'http-status-codes/'); await page.fill('#sq', '404'); const vis = await page.locator('#st tbody tr:visible').count(); assert.ok(vis >= 1 && vis <= 3 && (await page.locator('#st tbody tr:visible').first().textContent()).includes('Not Found')); });
  await t('mortgage page shows payment', async () => { await page.goto(calc + 'mortgage-calculator/'); await page.selectOption('#f-currency', 'USD'); await page.waitForTimeout(300); assert.ok((await page.textContent('#calc-out')).includes('$2,097.37')); });
  await t('tip presets work', async () => { await page.goto(calc + 'tip-calculator/'); await page.selectOption('#f-currency', 'USD'); await page.fill('#f-bill', '100'); await page.fill('#f-people', '4'); await page.click('[data-preset="20"]'); await page.waitForTimeout(300); assert.ok((await page.textContent('#calc-out')).includes('$30.00')); });
  await t('unit converter populates and converts', async () => { await page.goto(calc + 'unit-converter/'); await page.fill('#f-value', '1'); await page.selectOption('#f-cat', 'mass'); await page.selectOption('#f-from', 'kg'); await page.selectOption('#f-to', 'lb'); await page.waitForTimeout(300); assert.ok((await page.textContent('#calc-out')).includes('2.2046226')); });
  await t('dates: friendly empty state then result', async () => { await page.goto(calc + 'age-date-calculator/'); assert.ok((await page.textContent('#calc-out')).includes('Pick a start date')); await page.fill('#f-start', '2024-02-28'); await page.fill('#f-end', '2024-03-01'); await page.waitForTimeout(300); assert.ok((await page.textContent('#calc-out')).includes('0 y 0 m 2 d')); });
  await t('home search filters', async () => { await page.goto(calc); await page.fill('#find', 'tip'); assert.strictEqual(await page.locator('#calc-grid [data-find]:visible').count(), 1); });
  await t('no uncaught page errors', async () => { assert.deepStrictEqual(errs, []); });
  await b.close(); sDev.close(); sCalc.close(); console.log(fails ? fails + ' failing' : 'all passed'); process.exit(fails ? 1 : 0);
})();
