// Functional tests for the news/weather/eco sites with mocked live APIs (no real network).
const http = require('http'), fs = require('fs'), path = require('path'), assert = require('assert'); const pw = require('/opt/node22/lib/node_modules/playwright');
const M = { '.html': 'text/html', '.css': 'text/css', '.js': 'text/javascript', '.json': 'application/json' };
const serve = (dir) => new Promise((res) => { const s = http.createServer((q, r) => { let p = q.url.split('?')[0]; if (p.endsWith('/')) p += 'index.html'; const f = path.join(dir, p); if (!fs.existsSync(f)) { r.writeHead(404); return r.end(); } r.writeHead(200, { 'content-type': M[path.extname(f)] || 'text/plain' }); fs.createReadStream(f).pipe(r); }); s.listen(0, () => res(s)); });
const now = Math.floor(Date.now() / 1000);
const MOCK = [
  [/hn\.algolia\.com.*front_page/, { hits: [{ title: 'Front page story', url: 'https://example.org/f1', objectID: '1', created_at_i: now - 600, points: 120, num_comments: 40 }] }],
  [/hn\.algolia\.com/, { hits: [{ title: 'New open model beats benchmark', url: 'https://example.com/a1', objectID: '11', created_at_i: now - 300, points: 90, num_comments: 12 }, { title: 'Chatbot agent ships', url: 'https://example.com/a2', objectID: '12', created_at_i: now - 900, points: 50, num_comments: 3 }] }],
  [/huggingface\.co\/api\/daily_papers/, [{ title: 'A paper', publishedAt: new Date().toISOString(), paper: { id: '2501.0001', title: 'Scaling something', upvotes: 33 } }]],
  [/wikipedia\.org\/api\/rest_v1\/feed\/featured/, { news: [{ story: 'Something <a href="/wiki/X">happened</a> today.', links: [{ content_urls: { desktop: { page: 'https://en.wikipedia.org/wiki/X' } } }] }], onthisday: [{ text: 'A treaty was signed.', year: 1815, pages: [{ content_urls: { desktop: { page: 'https://en.wikipedia.org/wiki/Treaty' } } }] }, { text: 'A bridge opened.', year: 1932, pages: [] }], tfa: { titles: { normalized: 'Featured Thing' }, content_urls: { desktop: { page: 'https://en.wikipedia.org/wiki/Featured' } }, description: 'desc', extract: 'extract text' } }],
  [/geocoding-api\.open-meteo\.com/, { results: [{ name: 'Toronto', admin1: 'Ontario', country_code: 'CA', latitude: 43.7, longitude: -79.4 }] }],
  [/api\.open-meteo\.com/, { current: { temperature_2m: 12.4, apparent_temperature: 10.1, weather_code: 3, wind_speed_10m: 14, relative_humidity_2m: 71 }, daily: { time: [0, 1, 2, 3, 4, 5, 6].map((i) => new Date(Date.now() + i * 864e5).toISOString().slice(0, 10)), weather_code: [3, 61, 0, 1, 2, 95, 71], temperature_2m_max: [14, 13, 16, 18, 15, 12, 5], temperature_2m_min: [6, 7, 8, 9, 7, 5, -2], precipitation_probability_max: [10, 70, 0, 5, 20, 90, 60] } }]
];
(async () => {
  const b = await pw.chromium.launch(); const dist = path.join(__dirname, '..', 'dist'); let fails = 0;
  const S = {}; for (const k of ['ai-pulse', 'daily-brief', 'eco-steps']) { const s = await serve(path.join(dist, k)); S[k] = `http://127.0.0.1:${s.address().port}/`; S[k + '_s'] = s; }
  const ctx = await b.newContext({ viewport: { width: 1000, height: 900 }, locale: 'en-CA' }); const page = await ctx.newPage(); const errs = []; page.on('pageerror', (e) => errs.push(e.message));
  await page.route(/^https?:\/\/(?!127\.0\.0\.1)/, (rt) => { const u = rt.request().url(); for (const [re, body] of MOCK) if (re.test(u)) return rt.fulfill({ json: body }); rt.abort(); });
  const t = async (name, fn) => { try { await fn(); console.log('ok   ' + name); } catch (e) { fails++; console.log('FAIL ' + name + ': ' + e.message.split('\n')[0]); } };
  await t('ai-pulse home renders live HN items, deduped, newest first', async () => { await page.goto(S['ai-pulse']); await page.waitForSelector('#feed .news-item'); const titles = await page.locator('#feed .news-item h3').allTextContents(); assert.deepStrictEqual(titles, ['New open model beats benchmark', 'Chatbot agent ships']); assert.ok((await page.locator('#feed a.title').first().getAttribute('href')) === 'https://example.com/a1'); assert.ok((await page.locator('#feed a.title').first().getAttribute('rel')).includes('noopener')); });
  await t('ai-pulse search filters', async () => { await page.goto(S['ai-pulse'] + 'news/'); await page.waitForSelector('#feed .news-item'); await page.fill('#feed-search', 'chatbot'); await page.waitForTimeout(300); assert.strictEqual(await page.locator('#feed .news-item').count(), 1); await page.fill('#feed-search', 'zzzzzz'); await page.waitForTimeout(300); assert.match(await page.textContent('#feed'), /Nothing matches/); });
  await t('ai-pulse research page shows HF paper', async () => { await page.goto(S['ai-pulse'] + 'research/'); await page.waitForSelector('#feed .news-item'); assert.ok((await page.textContent('#feed')).includes('Scaling something')); });
  await t('ai-pulse glossary search', async () => { await page.goto(S['ai-pulse'] + 'glossary/'); await page.fill('#gq', 'hallucination'); const n = await page.locator('#gl [data-q]:visible').count(); assert.strictEqual(n, 1); });
  await t('ai-pulse feed degrades gracefully when offline', async () => { const p2 = await ctx.newPage(); await p2.route(/^https?:\/\/(?!127\.0\.0\.1)/, (rt) => rt.abort()); await p2.goto(S['ai-pulse']); await p2.waitForSelector('#feed .empty'); assert.match(await p2.textContent('#feed'), /could not be loaded/); await p2.close(); });
  await t('daily-brief home: wiki news + history + featured', async () => { await page.goto(S['daily-brief']); await page.waitForSelector('#feed .news-item'); assert.ok((await page.textContent('#feed')).includes('Something happened today.')); await page.waitForSelector('#hist li'); assert.ok((await page.textContent('#hist')).includes('1815')); assert.ok((await page.textContent('#today')).length > 8); });
  await t('daily-brief weather search + forecast', async () => { await page.goto(S['daily-brief'] + 'weather/'); await page.fill('#wx-q', 'Toronto'); await page.click('#wx-form button[type=submit]'); await page.waitForSelector('#wx-out .result'); const t = await page.textContent('#wx-out'); assert.ok(t.includes('Toronto') && t.includes('12°C') && t.includes('Thunderstorm')); assert.strictEqual(await page.locator('#wx-out tbody tr').count(), 7); await page.click('#wx-units'); await page.waitForSelector('#wx-out .result'); });
  await t('daily-brief weather remembers city on home (compact)', async () => { await page.goto(S['daily-brief']); await page.waitForSelector('#wx-out .result'); assert.ok((await page.textContent('#wx-out')).includes('Toronto')); });
  await t('daily-brief history page', async () => { await page.goto(S['daily-brief'] + 'today-in-history/'); await page.waitForSelector('#hist li'); await page.waitForSelector('#tfa h3'); assert.ok((await page.textContent('#tfa')).includes('Featured Thing')); });
  await t('eco footprint responds to inputs', async () => { await page.goto(S['eco-steps'] + 'carbon-footprint-calculator/'); await page.waitForSelector('#out .result'); const before = await page.textContent('#out .big'); await page.fill('#f-long', '3'); await page.waitForTimeout(300); const after = await page.textContent('#out .big'); assert.notStrictEqual(before, after); assert.ok(await page.locator('#out .bar').count() === 7); });
  await t('eco appliance presets', async () => { await page.goto(S['eco-steps'] + 'appliance-energy-cost-calculator/'); await page.click('[data-w="1500"]'); await page.waitForTimeout(200); assert.ok((await page.textContent('#out')).includes('kWh')); });
  await t('eco recycling search', async () => { await page.goto(S['eco-steps'] + 'recycling-guide/'); await page.fill('#rq', 'battery'); const nv = await page.locator('#rt tbody tr:visible').count(); assert.ok(nv >= 1 && nv < 5, 'visible rows ' + nv); });
  await t('eco checklist persists across reload', async () => { await page.goto(S['eco-steps'] + 'plastic-swap-checklist/'); await page.check('#s0'); await page.check('#s3'); assert.match(await page.textContent('#prog'), /2 of 20/); await page.reload(); assert.match(await page.textContent('#prog'), /2 of 20/); await page.click('#reset'); assert.match(await page.textContent('#prog'), /0 of 20/); });
  await t('consent: ads script does not load unless accepted', async () => {
    const dir = path.join(dist, 'eco-steps'); const cfgF = path.join(dir, 'assets', 'site-config.js'); const orig = fs.readFileSync(cfgF, 'utf8'); fs.writeFileSync(cfgF, 'window.SITE_CONFIG={"adsenseClient":"ca-pub-1234567890","slots":{"top":"1","mid":"2","bottom":"3"}};');
    try { const p3 = await ctx.newPage(); const reqs = []; p3.on('request', (r) => reqs.push(r.url())); await p3.route(/^https?:\/\/(?!127\.0\.0\.1)/, (rt) => rt.fulfill({ status: 200, contentType: 'text/javascript', body: '' })); await p3.goto(S['eco-steps']); await p3.waitForTimeout(400); assert.ok(await p3.isVisible('#consent')); assert.ok(!reqs.some((u) => /googlesyndication/.test(u)), 'ads loaded before consent'); await p3.click('#consent-yes'); await p3.waitForTimeout(400); assert.ok(reqs.some((u) => /googlesyndication/.test(u)), 'ads did not load after consent'); await p3.reload(); await p3.waitForTimeout(300); assert.ok(!(await p3.isVisible('#consent'))); await p3.close(); const p4 = await (await b.newContext()).newPage(); await p4.route(/^https?:\/\/(?!127\.0\.0\.1)/, (rt) => rt.abort()); await p4.goto(S['eco-steps']); await p4.click('#consent-no'); assert.ok(!(await p4.isVisible('#consent'))); }
    finally { fs.writeFileSync(cfgF, orig); }
  });
  await t('no uncaught page errors', async () => { assert.deepStrictEqual(errs, []); });
  await b.close(); Object.keys(S).filter((k) => k.endsWith('_s')).forEach((k) => S[k].close()); console.log(fails ? fails + ' failing' : 'all passed'); process.exit(fails ? 1 : 0);
})();
