module.exports = [
  { slug: 'what-is-a-large-language-model', emoji: '🧠', title: 'What is a large language model? A plain-English explanation', desc: 'How chatbots like the ones everyone talks about actually work, what they are good at, and where they go wrong.',
    html: `<p>If you have used an AI chatbot, you have used a <strong>large language model</strong>, or LLM. This guide explains how one works without any maths.</p>
<h2>The core idea: predict the next piece of text</h2><p>An LLM is a very large neural network trained on enormous amounts of text. During training it plays one game billions of times: given some text, guess the next small chunk (called a <em>token</em>). Each wrong guess nudges millions or billions of internal numbers (<em>parameters</em>) so the next guess is slightly better. After enough rounds, predicting the next token well requires picking up grammar, facts, writing styles, and even patterns of reasoning.</p>
<h2>From text predictor to helpful assistant</h2><p>A raw model just continues text. To turn it into an assistant, developers add steps: training on example conversations, and <em>reinforcement learning from human feedback</em>, where people rank answers and the model learns to prefer helpful, honest and safe ones. Hidden instructions (the <em>system prompt</em>) then set its role and limits.</p>
<!--AD-->
<h2>What LLMs are good at</h2><ul><li>Drafting, rewriting and summarising text</li><li>Explaining ideas at different levels</li><li>Translating between languages</li><li>Writing and explaining code</li><li>Brainstorming and organising information</li></ul>
<h2>Where they go wrong</h2><ul><li><strong>Hallucinations:</strong> they can state invented facts or fake sources fluently, because they generate plausible text, not verified truth.</li><li><strong>Out-of-date knowledge:</strong> a model only knows what was in its training data unless it can search the web or use documents.</li><li><strong>Maths and counting:</strong> they can slip on precise calculation unless they use a calculator tool.</li><li><strong>Bias:</strong> they can reflect biases in their training data.</li><li><strong>Manipulation:</strong> clever prompts can sometimes bypass safety rules (jailbreaks) or hide instructions in documents (prompt injection).</li></ul>
<h2>How to use them wisely</h2><p>Treat an LLM as a fast, knowledgeable but sometimes overconfident assistant. Check important facts against reliable sources, do not paste secrets, and keep a human in charge of decisions that affect health, money, law or safety.</p><p class="footnote">Want the vocabulary? See our <a href="../../glossary/">AI glossary</a>.</p>` },
  { slug: 'spot-ai-scams-and-deepfakes', emoji: '🛡️', title: 'How to spot AI scams and deepfakes', desc: 'Voice-cloning calls, fake videos and perfect-looking phishing: practical steps to protect yourself and your family.',
    html: `<p>Generative AI has made scams cheaper to produce and more convincing. The good news: the defences are mostly simple habits. This guide covers the most common tricks and what to do.</p>
<h2>1. Cloned voices and "family emergency" calls</h2><p>With a few seconds of audio from social media, criminals can imitate a relative's voice and phone claiming to be in trouble and needing money now. <strong>Defence:</strong> hang up and call the person back on a number you already know. Agree a family "safe word" that only you know. Be suspicious of any urgent request for gift cards, crypto or wire transfers.</p>
<h2>2. Deepfake video and fake endorsements</h2><p>Fake videos show celebrities or politicians promoting investments or saying things they never said. Look for: unnatural blinking or lip-sync, odd lighting or edges around the face and hair, hands and teeth that look wrong, and audio that does not match mouth movements. More reliable than spotting flaws: <strong>check the source</strong>. Does a trusted outlet report it? Is the account verified and long-standing? Search for the claim plus the word "fake".</p>
<!--AD-->
<h2>3. Perfectly written phishing</h2><p>Spelling mistakes used to give scams away. AI removes that clue. Instead, check the sender address, hover over links before clicking, and be wary of any message that creates urgency or asks you to log in. Go to the website directly by typing the address, not through the message.</p>
<h2>4. Fake reviews, websites and "AI" investment schemes</h2><p>Be sceptical of guaranteed returns, "AI trading bots", and shops with unrealistically low prices. Check how old a website is, look for real contact details, and prefer payment methods with buyer protection.</p>
<h2>5. Romance and chat scams</h2><p>AI can run a convincing chat persona around the clock. Never send money to someone you have only met online, no matter how real the relationship feels. Video calls can be faked too.</p>
<h2>What to do if you are targeted</h2><ul><li>Stop talking, do not click or pay.</li><li>Contact your bank immediately if money moved.</li><li>Report it to your national fraud centre (for example the Canadian Anti-Fraud Centre, the FTC in the US, or Action Fraud in the UK).</li><li>Tell friends and family - scammers repeat what works.</li></ul>
<p class="footnote">Stay calm: scammers rely on panic. Pausing for five minutes defeats most of them.</p>` },
  { slug: 'how-to-read-ai-news-without-the-hype', emoji: '📰', title: 'How to read AI news without the hype', desc: 'A checklist for judging AI headlines: benchmarks, demos, funding rounds and big promises.',
    html: `<p>AI coverage swings between miracle and doom. A few habits help you see what is actually new.</p>
<h2>Ask: what exactly was shown?</h2><ul><li><strong>A demo</strong> is not a product. Demos are chosen to look good; ask whether the public can use it and how often it fails.</li><li><strong>A research paper</strong> is a claim awaiting replication. Many results shrink or vanish when others try them.</li><li><strong>A product launch</strong> tells you what is available today, usually with limits and pricing.</li></ul>
<h2>Read benchmark claims carefully</h2><p>Benchmarks are standard tests. They are useful but imperfect: models can be tuned for them, test questions can leak into training data, and a high score on a narrow test does not guarantee real-world reliability. Look for results from independent evaluators, and for tests that match the work you care about.</p>
<!--AD-->
<h2>Follow the incentives</h2><p>Companies announce to attract customers, talent and investment. Founders predicting that their own field will change the world are not neutral sources. The same goes for critics selling fear. Prefer reporting that quotes outside experts and shows evidence.</p>
<h2>Watch the language</h2><ul><li>"Could", "may" and "up to" are not "will".</li><li>"AI-powered" often means ordinary software with a model added on.</li><li>"Human-level" or "PhD-level" refers to specific tests, not general ability.</li><li>Percentages without a baseline ("50% faster") need a "compared to what?"</li></ul>
<h2>Separate the layers</h2><p>Keep four things apart: <em>research</em> (what is possible), <em>products</em> (what you can use), <em>business</em> (money and competition) and <em>policy</em> (rules and safety). A funding record is business news, not proof that the technology works.</p>
<h2>Our approach</h2><p>AI Pulse links to original publishers and the primary sources (papers, company posts) whenever possible, and shows where each headline comes from, so you can judge for yourself.</p>` },
  { slug: 'prompting-basics', emoji: '💬', title: 'Prompting basics: how to get better answers from AI', desc: 'Seven simple techniques that make chatbots far more useful - with examples you can copy.',
    html: `<p>The quality of an AI answer depends heavily on the question. You do not need magic words, just clarity.</p>
<h2>1. Say who it is for and what you want</h2><p>Instead of "Explain inflation", try: "Explain inflation to a 15-year-old in 150 words, using an example about pizza prices."</p>
<h2>2. Give context</h2><p>Paste the relevant text, say your goal, and mention constraints (budget, tools, deadline). The model cannot read your mind or see your screen.</p>
<h2>3. Specify the format</h2><p>"Give me a table with three columns", "five bullet points", "a friendly email under 120 words", "JSON with these keys".</p>
<!--AD-->
<h2>4. Show an example</h2><p>One or two samples of the style you want ("here is a paragraph I like") often beats a long description.</p>
<h2>5. Break big jobs into steps</h2><p>Ask for an outline first, approve it, then request each section. For tricky problems, ask the model to think step by step.</p>
<h2>6. Ask it to check itself</h2><p>"List the assumptions you made", "what could be wrong with this answer?" or "give sources I can verify". Then verify them - models can invent citations.</p>
<h2>7. Iterate</h2><p>Treat it as a conversation. "Shorter", "more formal", "explain the second point more" all work.</p>
<h2>What not to do</h2><ul><li>Do not paste passwords, private customer data or confidential documents into tools you do not control.</li><li>Do not rely on a single answer for medical, legal or financial decisions.</li><li>Do not assume it knows today's news unless it can search the web.</li></ul>
<h2>A template to copy</h2><pre>Role: You are an experienced [role].
Task: [what you want done]
Context: [background, audience, constraints]
Format: [how the answer should look]
Check: Tell me anything you are unsure about.</pre>` },
  { slug: 'ai-privacy-what-to-share', emoji: '🔒', title: 'AI and your privacy: what you should (and should not) share', desc: 'How chatbots handle your data and a simple rule of thumb for what to keep to yourself.',
    html: `<p>Chatbots feel private, but your messages usually travel to a company\'s servers. Here is how to stay in control.</p>
<h2>What can happen to your conversations</h2><ul><li>They may be stored for a period of time for safety and operations.</li><li>Some services use them to improve their models unless you opt out - check the data controls in your settings.</li><li>Staff or automated systems may review some chats to catch abuse.</li><li>A hacked account or shared device can expose your history.</li></ul>
<h2>A simple rule: if you would not post it publicly, think twice</h2><p><strong>Avoid sharing:</strong> passwords and recovery codes, bank or card numbers, government ID numbers, private medical records, other people\'s personal details, confidential work documents, and anything covered by a contract or NDA.</p>
<!--AD-->
<h2>Safer habits</h2><ul><li>Use the privacy settings: turn off training on your data and use temporary or incognito chats where offered.</li><li>Remove names and numbers before pasting text ("Customer A", "[ACCOUNT]").</li><li>Use work-approved tools for work information.</li><li>Protect your account with a strong, unique password and two-factor authentication.</li><li>Review browser extensions and apps that say they add AI: they may read every page you visit.</li></ul>
<h2>Running AI on your own computer</h2><p>Open-weight models can run locally, so your text never leaves your machine. This takes a reasonably powerful computer but is the most private option.</p>
<h2>Children and AI</h2><p>Talk with children about not sharing real names, addresses, schools or photos with chatbots, and keep an eye on what AI tools they use.</p>
<h2>Your rights</h2><p>Depending on where you live (for example under GDPR in Europe or privacy laws in Canada and parts of the US) you may be able to access or delete data a company holds about you. Look for a privacy request form in the service\'s settings.</p>` },
  { slug: 'ai-safety-explained', emoji: '⚖️', title: 'AI safety explained: what researchers actually worry about', desc: 'Misuse, mistakes, bias, loss of control and security: the main risks of AI and what is being done about them.',
    html: `<p>"AI safety" covers a range of problems, from everyday harms happening now to bigger questions about powerful future systems. Here is a calm overview.</p>
<h2>1. Mistakes and hallucinations</h2><p>Models can be confidently wrong. In low-stakes uses that is an annoyance; in medicine, law or engineering it can hurt people. Mitigations: grounding answers in trusted documents, citations, and keeping humans responsible for decisions.</p>
<h2>2. Bias and fairness</h2><p>Systems trained on historical data can repeat or amplify unfair patterns in hiring, lending or policing. Mitigations: auditing, diverse data, testing across groups, and transparency.</p>
<h2>3. Misuse</h2><p>The same tools that write helpful emails can write scams, disinformation or malware. Developers use usage policies, monitoring, safety training and "red teaming" - deliberately attacking their own systems to find weaknesses.</p>
<!--AD-->
<h2>4. Security of AI itself</h2><p>AI systems have new attack surfaces: <em>prompt injection</em> (hidden instructions in content the AI reads), data poisoning, and theft of models. As assistants gain the ability to act - send emails, run code, spend money - these attacks matter more, so permissions should be limited and sensitive actions confirmed by a human.</p>
<h2>5. Alignment and control</h2><p>Alignment research asks how to make increasingly capable systems reliably do what we intend, even in situations nobody tested. It includes interpretability (understanding what happens inside models), oversight methods, and evaluating dangerous capabilities before release.</p>
<h2>6. Concentration of power and jobs</h2><p>Who controls the most capable systems, and how work and income change, are social questions as much as technical ones. Policy discussions include transparency rules, audits, and support for workers.</p>
<h2>What you can do</h2><ul><li>Stay curious and sceptical of both hype and doom.</li><li>Keep humans in the loop for important decisions.</li><li>Protect your own accounts and data.</li><li>Support transparency and independent testing.</li></ul>
<p class="footnote">Experts disagree about the likelihood and timing of the larger risks; this guide aims to describe the debate, not settle it.</p>` }
];
