const glossary = require('./glossary'), guides = require('./guides'), { card, esc } = require('../../lib/ui');
const site = {
  slug: 'ai-pulse', name: 'AI Pulse', tag: 'Daily AI news, explained simply', emoji: '⚡', accent: '#6d28d9', accentDark: '#c4b5fd', soft: '#f1eaff', softDark: '#251a42',
  desc: 'The latest AI news from trusted sources, plus plain-English guides, an AI glossary and safety tips. Updated throughout the day.',
  about: 'AI Pulse collects the day\'s artificial-intelligence headlines from publishers, research labs and the developer community, and pairs them with plain-English guides so you can understand what is happening - and what it means for you. We link to the original sources and never copy articles.',
  nav: [['News', 'news/'], ['Research', 'research/'], ['Guides', 'guides/'], ['Glossary', 'glossary/']], pages: []
};
const feed = (o = {}) => `<div class="row" style="margin:.4rem 0 1rem">${o.chips ? `<div class="chips" role="group" aria-label="Filter by topic">${o.chips.map(([k, l]) => `<button type="button" class="chip" data-topic="${k}" aria-pressed="false">${l}</button>`).join('')}</div>` : ''}${o.search ? '<label class="sr-only" for="feed-search">Search headlines</label><input id="feed-search" type="search" placeholder="Search headlines..." style="max-width:20rem">' : ''}</div><div class="grid wide" id="feed" data-json="data/news.json" data-live="${o.live || 'hn-ai'}" data-limit="${o.limit || 18}"${o.topic ? ` data-topic="${o.topic}"` : ''} aria-live="polite"></div><div class="row" style="margin-top:1rem"><button type="button" class="btn ghost" id="feed-more" hidden>Show more</button><span class="meta" id="feed-meta"></span></div><p class="footnote">Headlines link to their original publishers. Community links come from Hacker News. We do not copy article text.</p>`;
const NEWS_JS = ['assets/news.js'];
site.pages.push({ path: 'index.html', home: true, title: 'AI Pulse', nav: null, desc: site.desc, scripts: NEWS_JS, jsonld: { '@context': 'https://schema.org', '@type': 'WebSite', name: 'AI Pulse', description: site.desc },
  body: ({ rel, ad }) => `<section class="hero"><p class="eyebrow">Live AI headlines</p><h1>AI news you can actually follow</h1><p class="lead">The day\'s biggest AI stories from labs, publishers and the developer community - with plain-English guides to what it all means.</p></section>${ad('top')}
<h2>Latest AI headlines</h2>${feed({ limit: 12, chips: [['ai', 'AI'], ['research', 'Research'], ['industry', 'Industry'], ['policy', 'Policy']] })}${ad('mid')}
<section><h2>Start here</h2><div class="grid wide">${guides.slice(0, 3).map((g) => card(`${rel}guides/${g.slug}/`, g.emoji, g.title, g.desc)).join('')}</div><p><a class="btn ghost" href="${rel}guides/">All guides</a></p></section>
<section class="prose full"><h2>Why AI Pulse?</h2><p>AI moves fast and the coverage is noisy. We aim to cut through it: one place to see what is new, links straight to the source, and short explainers that do not assume a technical background. Learn the vocabulary in our <a href="${rel}glossary/">AI glossary</a> and stay safer online with our guides on <a href="${rel}guides/spot-ai-scams-and-deepfakes/">scams and deepfakes</a> and <a href="${rel}guides/ai-privacy-what-to-share/">privacy</a>.</p></section>${ad('bottom')}` });
site.pages.push({ path: 'news/index.html', title: 'Latest AI News', desc: 'Live feed of the latest artificial intelligence news from research labs, publishers and the developer community.', nav: 'news/', crumb: ['', ''], short: 'News', scripts: NEWS_JS,
  body: ({ ad }) => `<h1>Latest AI news</h1><p class="lead">Search and filter today\'s AI headlines.</p>${ad('top')}${feed({ limit: 24, search: true, chips: [['ai', 'AI'], ['research', 'Research'], ['industry', 'Industry'], ['policy', 'Policy']] })}${ad('bottom')}` });
site.pages.push({ path: 'research/index.html', title: 'AI Research Papers & Updates', desc: 'New AI research: daily trending papers and updates from major research labs, with links to the originals.', nav: 'research/', crumb: ['', ''], short: 'Research', scripts: NEWS_JS,
  body: ({ ad }) => `<h1>AI research</h1><p class="lead">Trending papers and lab updates. Research results are claims awaiting replication - read our <a href="../guides/how-to-read-ai-news-without-the-hype/">guide to reading AI news</a> for tips.</p>${ad('top')}${feed({ limit: 20, live: 'hf-papers', topic: 'research', search: true })}${ad('bottom')}` });
site.pages.push({ path: 'glossary/index.html', title: `AI Glossary: ${glossary.length} Terms Explained`, desc: 'Plain-English definitions of AI terms: LLM, token, hallucination, RAG, fine-tuning, alignment and more.', nav: 'glossary/', crumb: ['', ''], short: 'Glossary', scripts: ['assets/glossary.js'], jsonld: { '@context': 'https://schema.org', '@type': 'DefinedTermSet', name: 'AI Glossary', hasDefinedTerm: glossary.map(([t, d]) => ({ '@type': 'DefinedTerm', name: t, description: d })) },
  body: ({ ad }) => `<h1>AI glossary</h1><p class="lead">${glossary.length} terms, explained without jargon.</p>${ad('top')}<div class="row"><label class="sr-only" for="gq">Search the glossary</label><input id="gq" type="search" placeholder="Search terms..." style="max-width:22rem"></div><dl id="gl" class="prose full">${glossary.map(([t, d]) => `<div data-q="${esc((t + ' ' + d).toLowerCase())}"><dt id="${t.toLowerCase().replace(/[^a-z0-9]+/g, '-')}"><strong>${esc(t)}</strong></dt><dd>${esc(d)}</dd></div>`).join('')}</dl><p class="empty" id="gn" hidden>No term matches that search.</p>${ad('bottom')}` });
site.pages.push({ path: 'guides/index.html', title: 'AI Guides', desc: 'Plain-English AI guides: how LLMs work, spotting AI scams, prompting, privacy and safety.', nav: 'guides/', crumb: ['', ''], short: 'Guides',
  body: ({ rel, ad }) => `<h1>AI guides</h1><p class="lead">Clear explainers for curious people.</p>${ad('top')}<div class="grid wide">${guides.map((g) => card(`${rel}guides/${g.slug}/`, g.emoji, g.title, g.desc)).join('')}</div>${ad('bottom')}` });
for (const g of guides) site.pages.push({ path: `guides/${g.slug}/index.html`, title: g.title, desc: g.desc, nav: 'guides/', crumb: ['Guides', 'guides/'], short: g.title, jsonld: { '@context': 'https://schema.org', '@type': 'Article', headline: g.title, description: g.desc, dateModified: new Date().toISOString().slice(0, 10) },
  body: ({ rel, ad }) => `<article class="prose"><p class="eyebrow">Guide</p><h1>${esc(g.title)}</h1>${g.html.split('<!--AD-->')[0]}${ad('mid')}${g.html.split('<!--AD-->')[1] || ''}</article><section><h2>Keep reading</h2><div class="grid">${guides.filter((x) => x !== g).slice(0, 3).map((x) => card(`${rel}guides/${x.slug}/`, x.emoji, x.title, x.desc)).join('')}</div></section>${ad('bottom')}` });
module.exports = site;
