// Honest, plain-language legal pages shared by every site (not legal advice - Mason should have them reviewed before heavy traffic).
const { esc } = require('./layout');
module.exports = function legalPages(site) {
  const N = esc(site.name), upd = new Date().toISOString().slice(0, 10);
  const wrap = (title, body) => `<article class="prose"><h1>${title}</h1><p class="muted">Last updated: ${upd}</p>${body}</article>`;
  return [
    { path: 'about/index.html', title: 'About', desc: `About ${site.name}: who makes it, why it exists and how we keep it free, fast and private.`, crumb: ['', ''], nav: null, body: wrap('About ' + N, `<p>${esc(site.about)}</p><p>${N} is one of five free, ad-supported sites built by Masons-coding. We keep them fast, accessible and useful on every screen from a small phone to a huge monitor. Nothing here asks you to sign up.</p><p>Spotted a mistake? Please tell us on the <a href="../contact/">contact page</a> - we fix errors quickly.</p>`) },
    { path: 'privacy/index.html', title: 'Privacy policy', desc: `Privacy policy for ${site.name}`, crumb: ['', ''], body: wrap('Privacy policy', `<p>Short version: we do not ask for your name or email, we do not run accounts, and the tools on ${N} work in your browser - what you type into them is not sent to us.</p><h2>What we collect</h2><p>We do not collect personal information through the tools. Our host (a static web host) may keep standard server logs such as IP address, page and time for security and reliability.</p><h2>Cookies and ads</h2><p>We may show advertising from Google AdSense to pay for the site. Ads load <strong>only after you press "Accept ads"</strong>. If you accept, Google and its partners may use cookies or similar technology to show and measure ads, which can include personalised ads where allowed. You can change your mind at any time with the "Ad choices" link in the footer, which clears your saved choice. You can also manage Google ad personalisation at <a href="https://adssettings.google.com" rel="noopener">adssettings.google.com</a>.</p><h2>What is saved on your device</h2><p>Your light/dark theme choice, your ad choice and, for some tools, your last inputs may be stored in your browser's local storage. This never leaves your device and you can clear it in your browser settings.</p><h2>External services</h2><p>Some pages fetch public information (for example headlines or weather) directly from third-party services in your browser. Those services will see your IP address as with any website. Links leave this site and have their own policies.</p><h2>Children</h2><p>${N} is not directed at children under 13 and does not knowingly collect their data.</p><h2>Your rights</h2><p>Because we hold no personal data about you, there is usually nothing to access or delete. If you believe we hold something, use the <a href="../contact/">contact page</a>.</p>`) },
    { path: 'terms/index.html', title: 'Terms of use', desc: `Terms of use for ${site.name}`, crumb: ['', ''], body: wrap('Terms of use', `<p>By using ${N} you agree to these simple terms.</p><ul><li><strong>General information only.</strong> Content and tool results are for information and are not financial, medical, legal, safety or professional advice. Check important numbers yourself and ask a qualified person before making big decisions.</li><li><strong>No warranty.</strong> We work hard to be accurate, but the site is provided "as is" and we are not liable for losses from using it.</li><li><strong>Fair use.</strong> Do not try to break, overload or scrape the site abusively.</li><li><strong>Links and news.</strong> Headlines link to the original publishers, who own their content. We show titles and short attributions only.</li><li><strong>Changes.</strong> We may update the site and these terms. Continued use means you accept the changes.</li></ul>`) },
    { path: 'contact/index.html', title: 'Contact', desc: `How to contact ${site.name}: report a mistake, suggest a tool or guide, or ask for something to be removed.`, crumb: ['', ''], body: wrap('Contact', `<p>Found an error, have a suggestion for a tool or guide, or want something removed? Open an issue on our public tracker and we will take a look:</p><p><a class="btn" href="${esc(site.issues)}" rel="noopener">Open an issue on GitHub</a></p><p class="muted">Please do not include passwords, personal details or private information in a public issue.</p>`) },
  ];
};
