module.exports = [
  { slug: 'spot-misinformation', emoji: '🔍', title: 'How to spot misinformation: a 6-step checklist', desc: 'Quick checks anyone can use before believing or sharing a shocking story.',
    html: `<p>False and misleading stories spread faster than corrections, often because they make us feel something strong. A short pause and a few checks protect you and the people you share with.</p>
<h2>1. Pause when you feel strong emotion</h2><p>Anger, fear and outrage are what misleading content is designed to trigger. If a post makes you want to share instantly, that is the moment to check.</p>
<h2>2. Check who is behind it</h2><p>Is the publisher real, with a track record, an "About" page, named authors and a corrections policy? Look at the web address carefully: lookalike domains imitate real outlets. Be wary of anonymous accounts and pages created recently.</p>
<h2>3. Read beyond the headline</h2><p>Headlines are written to get clicks. The article may say something quite different, or nothing to support the claim. Check the date too: old stories resurface as "new".</p>
<!--AD-->
<h2>4. Find the original source</h2><p>Does the story link to the actual study, document, video or statement? A screenshot is not a source. Search for the quote or claim to find the earliest version.</p>
<h2>5. See what others report</h2><p>If something big happened, several independent, reputable outlets will cover it. If only one site or one social account has it, be careful. Fact-checking organisations (such as the International Fact-Checking Network members, Snopes, Reuters Fact Check, AFP Fact Check) may already have examined it.</p>
<h2>6. Check images and video</h2><p>Use a reverse image search (Google Lens, TinEye) to see where a photo first appeared. Images can be old, edited, AI-generated, or from a different place or event. Watch for odd details and mismatched audio in video.</p>
<h2>Common tricks</h2><ul><li><strong>Out of context:</strong> real image or quote, wrong time or place.</li><li><strong>Cherry-picked numbers:</strong> true figures that leave out the bigger picture.</li><li><strong>Fake experts:</strong> "a scientist says" without a name or credentials.</li><li><strong>Satire taken seriously:</strong> check whether the site is a joke.</li></ul>
<p class="footnote">When unsure, do not share. Staying quiet costs nothing; spreading a falsehood can.</p>` },
  { slug: 'five-minute-news-routine', emoji: '☕', title: 'A calm 5-minute daily news routine', desc: 'How to stay informed without doomscrolling: a simple routine that fits into your morning.',
    html: `<p>Constant news alerts can leave us anxious yet no better informed. A short, deliberate routine gives you the essentials and your attention back.</p>
<h2>The routine</h2><ol><li><strong>Minute 1 - Weather and day ahead.</strong> Check the forecast and anything that affects your commute or plans.</li><li><strong>Minutes 2-3 - Top headlines.</strong> Scan the main stories from a few different reputable sources. Read only the headlines and, for one or two stories that matter to you, the first paragraphs.</li><li><strong>Minute 4 - One topic you care about.</strong> Technology, science, business, health or your local area.</li><li><strong>Minute 5 - Something to learn or enjoy.</strong> This day in history, a featured article, or a long read saved for later.</li></ol>
<!--AD-->
<h2>Make it stick</h2><ul><li>Use a fixed time (with the first coffee) and a fixed place so it becomes a habit.</li><li>Turn off most news notifications; keep only genuine safety alerts.</li><li>Pick two or three sources with different viewpoints and a reputation for corrections.</li><li>Decide a stop point. News has no end; your attention does.</li></ul>
<h2>Why it helps</h2><p>Research on media habits has linked heavy, repeated exposure to negative news with higher stress. Most breaking news is also revised within hours, so waiting for a daily summary often gives you a more accurate picture.</p>
<h2>Do something with what you read</h2><p>If a story bothers you, choose one small action: donate, volunteer, contact a representative, or help a neighbour. Agency is the best antidote to news anxiety.</p>` },
  { slug: 'reading-statistics-in-the-news', emoji: '📊', title: 'How to read statistics in the news', desc: 'Percentages, averages, polls and "risk": the questions to ask when numbers show up in a headline.',
    html: `<p>Numbers make a story sound authoritative, but they can mislead even when they are accurate. Here are the questions that matter.</p>
<h2>Compared to what?</h2><p>"Cases doubled" sounds alarming; going from 2 to 4 cases is different from going from 2,000 to 4,000. Ask for the absolute numbers and the baseline. A "50% higher risk" of something that affects 2 in 100,000 people means the risk goes from 2 to 3 in 100,000.</p>
<h2>Average of what?</h2><p>The <em>mean</em> can be pulled up by a few very large values (average income), while the <em>median</em> (the middle value) is often a better picture of a typical person. Check which is used.</p>
<!--AD-->
<h2>Polls and margin of error</h2><p>A poll of about 1,000 people carries a margin of error of roughly three percentage points. If one candidate leads 48-46, that gap is within the noise. Also look at who was asked, how (phone, online), and how the question was worded.</p>
<h2>Correlation is not causation</h2><p>Ice cream sales and drownings both rise in summer; ice cream does not cause drowning. When a study says two things are "linked", ask whether something else (like hot weather) could explain both.</p>
<h2>Sample size and who was studied</h2><p>Small studies and studies on mice or on a narrow group may not apply to you. A single study is a starting point; many consistent studies, or a systematic review, are stronger.</p>
<h2>Charts</h2><p>Watch the axis: a chart that starts at 50 instead of 0 makes small changes look dramatic. Check units, time ranges and whether the data were adjusted for population or inflation.</p>
<h2>Quick checklist</h2><ul><li>What is the source of the number?</li><li>How big is the sample, and who is in it?</li><li>Absolute or relative change?</li><li>What is left out?</li></ul>` }
];
