const guides = require('./guides'), { card, esc } = require('../../lib/ui');
const site = {
  slug: 'daily-brief', name: 'Daily Brief', tag: 'Your 5-minute daily news, weather and history', emoji: '🗞️', accent: '#b45309', accentDark: '#fbbf24', soft: '#fdf1de', softDark: '#33230f',
  desc: 'A calm, quick daily briefing: top world headlines, tech and science news, your local weather forecast, and what happened on this day in history.',
  about: 'Daily Brief gives you a calm five-minute start to the day: the main headlines from reputable publishers, a local weather forecast and a look back at this day in history. We link to the original publishers and never copy their articles.',
  nav: [['Headlines', 'headlines/'], ['Weather', 'weather/'], ['This day', 'today-in-history/'], ['Guides', 'guides/']], pages: []
};
const NEWS_JS = ['assets/news.js'];
const feed = (o = {}) => `<div class="row" style="margin:.4rem 0 1rem">${o.chips ? `<div class="chips" role="group" aria-label="Filter by topic">${o.chips.map(([k, l]) => `<button type="button" class="chip" data-topic="${k}" aria-pressed="false">${l}</button>`).join('')}</div>` : ''}${o.search ? '<label class="sr-only" for="feed-search">Search headlines</label><input id="feed-search" type="search" placeholder="Search headlines..." style="max-width:20rem">' : ''}</div><div class="grid wide" id="feed" data-json="data/news.json" data-live="${o.live || 'wiki-news'}" data-limit="${o.limit || 18}"${o.topic ? ` data-topic="${o.topic}"` : ''} aria-live="polite"></div><div class="row" style="margin-top:1rem"><button type="button" class="btn ghost" id="feed-more" hidden>Show more</button><span class="meta" id="feed-meta"></span></div><p class="footnote">Headlines link to their original publishers; we show titles only. Wikipedia text is CC BY-SA 4.0.</p>`;
const CHIPS = [['world', 'World'], ['canada', 'Canada'], ['tech', 'Tech'], ['science', 'Science'], ['business', 'Business'], ['health', 'Health']];
site.pages.push({ path: 'index.html', home: true, title: 'Daily Brief', nav: null, desc: site.desc, scripts: [...NEWS_JS, 'assets/weather.js', 'assets/history.js'], jsonld: { '@context': 'https://schema.org', '@type': 'WebSite', name: 'Daily Brief', description: site.desc },
  body: ({ rel, ad }) => `<section class="hero"><p class="eyebrow" id="today">Your daily briefing</p><h1>The day in five minutes</h1><p class="lead">Top headlines, today\'s weather and a look back in history - calm, quick and clear.</p></section>${ad('top')}
<div class="tool"><section class="panel"><h2>Weather</h2><div id="wx" data-compact></div></section><section class="panel"><h2>On this day in history</h2><div id="hist" data-limit="6"><p class="loading">Loading...</p></div><p><a href="${rel}today-in-history/">More from history</a></p></section></div>
<h2>Top headlines</h2>${feed({ limit: 12, chips: CHIPS })}${ad('mid')}
<section><h2>Read and think</h2><div class="grid wide">${guides.map((g) => card(`${rel}guides/${g.slug}/`, g.emoji, g.title, g.desc)).join('')}</div></section>${ad('bottom')}
<script>(function(){var e=document.getElementById('today');if(e){try{e.textContent=new Date().toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'})}catch(x){}}})();</script>` });
site.pages.push({ path: 'headlines/index.html', title: 'Today\'s Headlines', desc: 'Search and filter today\'s top headlines from world, Canada, technology, science, business and health.', nav: 'headlines/', crumb: ['', ''], short: 'Headlines', scripts: NEWS_JS,
  body: ({ ad }) => `<h1>Today\'s headlines</h1><p class="lead">Filter by topic or search across all stories.</p>${ad('top')}${feed({ limit: 24, chips: CHIPS, search: true, live: 'wiki-news,hn-front' })}${ad('bottom')}` });
site.pages.push({ path: 'weather/index.html', title: 'Weather Forecast - 7 Day', desc: 'Free 7-day weather forecast for any city: temperature, rain chance, wind and humidity. No sign-up.', nav: 'weather/', crumb: ['', ''], short: 'Weather', scripts: ['assets/weather.js'],
  body: ({ ad }) => `<h1>Weather forecast</h1><p class="lead">Search for your city or share your device location to see the current conditions and the week ahead. Your location stays in this browser.</p>${ad('top')}<div id="wx"></div><article class="prose full"><h2>Reading a forecast</h2><ul><li><strong>Rain chance</strong> is the probability that measurable rain falls at a given point during the period - not how much or how long.</li><li><strong>Feels like</strong> combines temperature with wind and humidity to estimate how the air feels on your skin.</li><li>Forecasts are most reliable for the next 2-3 days and become less certain beyond 5-7.</li><li>Check an official source (such as your national weather service) for severe-weather warnings.</li></ul></article>${ad('bottom')}` });
site.pages.push({ path: 'today-in-history/index.html', title: 'This Day in History', desc: 'What happened on this day in history, plus today\'s featured article from Wikipedia.', nav: 'today-in-history/', crumb: ['', ''], short: 'This day in history', scripts: [...NEWS_JS, 'assets/history.js'],
  body: ({ ad }) => `<h1>This day in history</h1><p class="lead">Events from this date across the centuries.</p>${ad('top')}<div id="hist" data-limit="24"><p class="loading">Loading...</p></div>${ad('mid')}<h2>Featured article</h2><div id="tfa" class="card"><p class="loading">Loading...</p></div>${ad('bottom')}` });
site.pages.push({ path: 'guides/index.html', title: 'Guides: Reading the News Well', desc: 'Guides to spotting misinformation, reading statistics and building a calm daily news habit.', nav: 'guides/', crumb: ['', ''], short: 'Guides',
  body: ({ rel, ad }) => `<h1>Guides</h1><p class="lead">Get more from the news with less stress.</p>${ad('top')}<div class="grid wide">${guides.map((g) => card(`${rel}guides/${g.slug}/`, g.emoji, g.title, g.desc)).join('')}</div>${ad('bottom')}` });
for (const g of guides) site.pages.push({ path: `guides/${g.slug}/index.html`, title: g.title, desc: g.desc, nav: 'guides/', crumb: ['Guides', 'guides/'], short: g.title, jsonld: { '@context': 'https://schema.org', '@type': 'Article', headline: g.title, description: g.desc, dateModified: new Date().toISOString().slice(0, 10) },
  body: ({ rel, ad }) => `<article class="prose"><p class="eyebrow">Guide</p><h1>${esc(g.title)}</h1>${g.html.split('<!--AD-->')[0]}${ad('mid')}${g.html.split('<!--AD-->')[1] || ''}</article><section><h2>Keep reading</h2><div class="grid">${guides.filter((x) => x !== g).map((x) => card(`${rel}guides/${x.slug}/`, x.emoji, x.title, x.desc)).join('')}</div></section>${ad('bottom')}` });
module.exports = site;
