// [item, usual bin, tip]  - rules vary by city; always check your local program.
exports.recycling = [
  ['Aluminum cans', 'Recycling', 'Empty and give a quick rinse. Infinitely recyclable and very valuable.'], ['Steel / tin food cans', 'Recycling', 'Rinse; labels can stay on. Lids can go in the can.'], ['Glass bottles & jars', 'Recycling (or glass depot)', 'Rinse and remove lids. Not window glass, mirrors, or drinking glasses.'],
  ['Cardboard boxes', 'Recycling', 'Flatten. Greasy pizza-box lids are best composted or thrown away.'], ['Paper & newspaper', 'Recycling', 'Keep dry and clean. Shredded paper: check if your program accepts it in a paper bag.'], ['Milk & juice cartons', 'Recycling (most areas)', 'Rinse and flatten. Some areas want them with containers, others with paper.'],
  ['Plastic bottles (#1 PET, #2 HDPE)', 'Recycling', 'Empty and replace the cap. These are the most widely accepted plastics.'], ['Plastic tubs & jugs', 'Recycling', 'Rinse. Check numbers; #5 (PP) is accepted in many places.'], ['Plastic bags & film', 'Store drop-off (not curbside)', 'Bags jam sorting machines. Return clean, dry bags to grocery-store collection bins, or reuse them.'], ['Styrofoam (polystyrene)', 'Garbage or special depot', 'Rarely accepted curbside. Avoid it where you can.'],
  ['Takeout coffee cups', 'Usually garbage', 'Plastic lining makes most cups hard to recycle. Bring a reusable cup.'], ['Pizza boxes', 'Compost if greasy', 'Clean top lid can be recycled; the greasy bottom goes to compost or garbage.'], ['Food scraps', 'Compost / green bin', 'Fruit, veg, coffee grounds, eggshells. No plastic bags unless certified compostable and accepted.'], ['Yard waste', 'Compost / yard-waste collection', 'Leaves, grass, small branches.'],
  ['Batteries (household)', 'Hazardous waste / store drop-off', 'Never in garbage or recycling: they can start fires. Tape terminals on lithium batteries.'], ['Phones, laptops & electronics', 'E-waste depot', 'Wipe your data first. Many stores take old electronics back.'], ['Light bulbs (LED / CFL)', 'Hazardous waste / store drop-off', 'CFLs contain a small amount of mercury.'], ['Paint & solvents', 'Hazardous waste depot', 'Never pour down the drain. Donate leftover paint if possible.'],
  ['Clothing & textiles', 'Donate / textile bin', 'Wearable items to charity shops; worn-out textiles to textile-recycling bins. Do not put in recycling.'], ['Aerosol cans (empty)', 'Recycling in many areas', 'Only when completely empty; otherwise hazardous waste.'], ['Foil & foil trays', 'Recycling in many areas', 'Clean and scrunch into a ball bigger than a fist.'], ['Receipts (thermal paper)', 'Garbage', 'Chemical coating makes them unsuitable for paper recycling.'],
  ['Diapers', 'Garbage', 'Not recyclable or compostable in most places.'], ['Broken ceramics & mirrors', 'Garbage', 'Different melting point from container glass; wrap sharp pieces safely.'], ['Medication', 'Pharmacy take-back', 'Do not flush or bin them.'], ['Cooking oil', 'Depot or sealed container to garbage', 'Never pour into drains. Some cities collect used oil.'], ['Tires', 'Tire retailer or depot', 'Retailers usually take old tires when you buy new ones.'], ['Bubble wrap & plastic mailers', 'Store drop-off / reuse', 'Often accepted with plastic bags at drop-off points. Reuse for shipping.'], ['Wine corks', 'Cork collection / compost', 'Natural cork can be composted or collected by specialist programs.'], ['Printer cartridges', 'Retailer take-back', 'Most office stores and manufacturers accept them.']
];
exports.swaps = [
  ['Reusable water bottle', 'A single refillable bottle can replace hundreds of single-use bottles a year.'], ['Reusable shopping bags (keep them by the door)', 'Cuts single-use bags; wash cloth bags regularly.'], ['Reusable coffee cup', 'Most disposable cups have a plastic lining and are hard to recycle.'], ['Say no to straws and plastic cutlery', 'Skip them at takeout; carry a spare set.'],
  ['Refillable containers for lunches', 'Swap plastic wrap and bags for containers or beeswax wraps.'], ['Bar soap & shampoo bars', 'Replaces plastic bottles; lasts a long time.'], ['Bamboo or refillable toothbrush', 'Choose a compostable handle or replaceable head.'], ['Safety or reusable razor', 'Replaces dozens of disposable razors.'],
  ['Buy loose fruit and vegetables', 'Skip the produce bags, or use reusable mesh ones.'], ['Buy in bulk with your own jars', 'Lowers packaging; refill stores make it easy.'], ['Cloth napkins & rags', 'Replace paper towels for most household jobs.'], ['Concentrated or refill cleaning products', 'Powders, tablets and refills ship less water and plastic.'],
  ['Wash clothes with a microfibre filter bag or filter', 'Synthetic clothing sheds tiny fibres that end up in waterways.'], ['Choose natural-fibre or second-hand clothes', 'The longest-lived garment is the one already made.'], ['Repair before you replace', 'Fix shoes, electronics and clothes; ask about repair cafes.'], ['Return plastic bags & film to drop-off bins', 'Keeps them out of the garbage stream when no curbside option exists.'],
  ['Pick up litter on your walks (with a glove or tool)', 'Small actions add up. Never touch needles or hazards.'], ['Choose products with less plastic packaging', 'Vote with your wallet for glass, metal, paper or none.'], ['Use a refillable pen and tape-free packaging', 'Small desk-drawer changes cut waste.'], ['Support a local cleanup', 'Join or organise one - see our cleanup planner.']
];
exports.cleanup = [
  ['Before the day', [['Pick a location and time (low tide for beaches, daylight hours)', 'Choose public land or get permission from the owner or local authority.'], ['Check the weather and tide tables', 'Cancel or reschedule for storms, extreme heat or high surf.'], ['Tell the city or park about your plan', 'They may lend equipment, collect the bags and advise on hazards.'], ['Recruit friends, family or neighbours', 'Groups of 5-20 are easy to manage. Invite local clubs and schools.'], ['Set up a sign-up list and share meeting details', 'Include time, place, what to wear and what to bring.'], ['Plan waste disposal', 'Agree where full bags go and how recyclables will be separated.']]],
  ['Supplies', [['Reusable gloves for everyone (work or garden gloves)', 'Thicker gloves protect hands from sharp edges.'], ['Sturdy trash bags and a separate bag for recyclables', 'Use strong bags; do not overfill them (heavy bags tear and hurt backs).'], ['Litter pickers / grabber tools', 'Reduce bending and keep hands away from hazards.'], ['Buckets for small items', 'Great for cigarette butts, bottle caps and micro-plastics.'], ['First-aid kit', 'Bandages, antiseptic wipes, tweezers and a way to call for help.'], ['Water, sunscreen, hats and snacks', 'Stay hydrated and sun-safe.'], ['Hand sanitiser or wash station', 'Clean up before eating.'], ['Sharps container (for adult use only)', 'Only if the organiser is trained; otherwise report needles to the authorities.'], ['Scale or tally sheet and pens', 'Track bags and weight to show the impact (and report to community databases).'], ['Camera or phone for photos', 'Photograph the before and after (avoid showing faces without permission).']]],
  ['Safety briefing', [['Wear closed-toe shoes and weather-appropriate clothing', 'Sturdy boots on rough ground.'], ['Do not touch needles, broken glass in large amounts, chemicals, dead animals or unknown containers', 'Mark the spot and report it to local authorities.'], ['Stay away from water edges, slopes and traffic', 'Children must be supervised at all times by an adult.'], ['Use the buddy system and agree a meeting point', 'Count heads at the start and end.'], ['Lift with your legs; do not carry heavy loads alone', 'Use two people for bulky items.'], ['Respect wildlife and habitats', 'Leave nests, driftwood homes and dune plants alone.']]],
  ['On the day', [['Welcome everyone and explain the safety rules', 'Take 5 minutes: the plan, the zones and the finish time.'], ['Divide the area into zones with team leaders', 'Make sure every zone has a bag-and-tool kit.'], ['Sort recyclables as you go', 'Glass, metal, plastic and general waste if your area can process them.'], ['Take a break and drink water', 'Rotate tasks to avoid fatigue.'], ['Weigh or count what you collected', 'Record top items: cigarette butts, plastic bottles, wrappers and fishing gear.']]],
  ['After the cleanup', [['Dispose of waste as agreed', 'Confirm with the city or recycling depot.'], ['Wash hands and tools', 'Wash reusable gloves and equipment.'], ['Thank volunteers and share the results', 'Post photos and numbers (without personal details).'], ['Report data to a citizen-science project', 'Many ocean and river organisations collect litter data to support policy.'], ['Plan the next one', 'A regular schedule (monthly or seasonal) builds community.']]]
];
