module.exports = [
  { slug: 'reduce-plastic-at-home', emoji: '♻️', title: '15 easy ways to use less plastic at home', desc: 'Practical, low-cost swaps that cut single-use plastic in the kitchen, bathroom, shopping and on the go.',
    html: `<p>Plastic is useful, but single-use plastic is the problem: we use it for minutes and it lasts for centuries. You do not need a perfect plastic-free life. Start with the items you use most often.</p>
<h2>In the kitchen</h2><ol><li><strong>Use a reusable bottle</strong> and fill it at home; carry it everywhere.</li><li><strong>Replace cling film</strong> with containers, plates over bowls, or beeswax or silicone covers.</li><li><strong>Buy loose produce</strong> and bring your own bags or mesh.</li><li><strong>Choose bulk or refill</strong> for pasta, rice, nuts and cleaning products.</li><li><strong>Swap sponges</strong> for cloths or natural-fibre scrubbers.</li></ol>
<h2>In the bathroom</h2><ol start="6"><li><strong>Bar soap and shampoo bars</strong> replace bottles.</li><li><strong>A bamboo toothbrush or a refillable electric head</strong> reduces waste.</li><li><strong>A safety razor</strong> replaces a lifetime of plastic razors.</li><li><strong>Skip microbead products</strong> (most countries have banned them, but check ingredients like polyethylene).</li></ol>
<!--AD-->
<h2>On the go</h2><ol start="10"><li><strong>Carry a reusable bag, cup and cutlery set</strong>. Keep a bag in your car, coat and backpack.</li><li><strong>Say "no straw, no lid"</strong> when you order, if you can.</li><li><strong>Pack lunch</strong> in reusable containers.</li></ol>
<h2>Shopping and beyond</h2><ol start="13"><li><strong>Choose products with less packaging</strong>, or in glass, metal or cardboard.</li><li><strong>Buy fewer things, and repair what you have.</strong></li><li><strong>Recycle properly</strong> - clean, dry and sorted according to your local rules (see our <a href="../../recycling-guide/">recycling guide</a>).</li></ol>
<h2>Tips for making it stick</h2><ul><li>Change one habit a week rather than everything at once.</li><li>Use up what you have before buying replacements - throwing away plastic items to buy "eco" versions can create more waste.</li><li>Do not feel guilty about the imperfections. Collective action and policy change matter most, and every habit helps.</li></ul>
<p>Track your progress with our <a href="../../plastic-swap-checklist/">plastic swap checklist</a>.</p>` },
  { slug: 'ocean-plastic-explained', emoji: '🌊', title: 'Ocean plastic explained: where it comes from and what helps', desc: 'How plastic reaches the sea, why microplastics matter, and what cleanups and everyday choices can do.',
    html: `<p>Millions of tonnes of plastic enter the world\'s oceans every year; estimates vary with the method used, but all point to a very large problem. Understanding where it comes from shows where our effort works best.</p>
<h2>Where does it come from?</h2><p>Most ocean plastic starts on land. Litter and poorly managed waste are washed or blown into storm drains, streams and rivers, and carried to the sea. Other sources include fishing gear (lost nets and lines), tyre and textile particles, and spills of plastic pellets used to make products. Rivers - especially in places where waste collection is limited - are major pathways.</p>
<h2>Macroplastics and microplastics</h2><p>Larger items such as bottles, bags and nets can entangle or be swallowed by wildlife. In sunlight and waves they slowly fragment into <strong>microplastics</strong> (smaller than 5 millimetres), which cannot be cleaned up from the water and have been found from deep trenches to polar ice. Research on their effects on animals and human health is ongoing, which is a reason to reduce them at the source.</p>
<h2>The "garbage patches"</h2><p>Currents gather floating debris into regions such as the Great Pacific Garbage Patch. It is better described as a vast area of scattered fragments than a solid island; much plastic also sinks or lands on shorelines.</p>
<!--AD-->
<h2>What helps most</h2><ol><li><strong>Turn off the tap:</strong> reducing single-use plastic, improving waste collection and recycling, and designing products to be reusable matter more than cleaning the sea afterwards.</li><li><strong>Catch it in rivers:</strong> barriers and trash traps in waterways stop plastic before it reaches the ocean.</li><li><strong>Shoreline cleanups:</strong> they remove debris before it fragments and give communities data to support policy.</li><li><strong>Policy:</strong> bans on certain single-use items, deposit-return schemes and producer responsibility rules have shown results.</li></ol>
<h2>What you can do this month</h2><ul><li>Join or organise a local cleanup (see our <a href="../../cleanup-planner/">cleanup planner</a>).</li><li>Make three plastic swaps and track them on the <a href="../../plastic-swap-checklist/">checklist</a>.</li><li>Put litter in bins; secure your recycling and trash on windy days.</li><li>Support organisations and policies working on prevention.</li></ul>
<p class="footnote">Figures and effects are active research areas; consult scientific bodies such as UNEP and NOAA for the latest data.</p>` },
  { slug: 'save-energy-at-home', emoji: '💡', title: 'Save energy at home: the biggest wins first', desc: 'Where home energy goes and the simple changes that cut bills and emissions the most.',
    html: `<p>Heating and cooling usually account for around half of a household\'s energy use, followed by water heating, appliances and lighting. Focusing on the big items saves more than hunting for tiny savings.</p>
<h2>1. Heating and cooling</h2><ul><li>Lower the thermostat by 1-2 degrees in winter (and raise it in summer). Each degree can save a few percent on heating costs.</li><li>Use a programmable or smart thermostat to reduce heating when you are asleep or away.</li><li>Seal drafts around doors and windows; add insulation in the attic, which is often the cheapest big upgrade.</li><li>Service your furnace or heat pump and replace filters regularly. Heat pumps are far more efficient than electric resistance heating.</li></ul>
<h2>2. Hot water</h2><ul><li>Take shorter showers and fit a low-flow showerhead.</li><li>Turn your water heater down to about 50-55&deg;C (120-130&deg;F); do not go below 50&deg;C (risk of bacteria) and do not set it so high that it scalds.</li><li>Wash clothes in cold water - detergent works well and most of a washing machine\'s energy goes to heating the water.</li></ul>
<!--AD-->
<h2>3. Lighting and appliances</h2><ul><li>Switch to LED bulbs: they use about 75-80% less energy than old incandescent bulbs and last much longer.</li><li>Unplug or use power strips for devices with standby drain: games consoles, TVs, chargers, old computers.</li><li>When replacing appliances, check the energy rating (such as ENERGY STAR).</li><li>Air-dry clothes when you can and run full loads in the dishwasher.</li></ul>
<h2>4. The fridge</h2><p>Keep the fridge at about 3-4&deg;C and the freezer at -18&deg;C, vacuum the coils, and check the door seal. An old second fridge in the garage can be a surprisingly large energy drain.</p>
<h2>5. Think big: electricity source and transport</h2><p>If your area allows, choose renewable electricity or install solar. For transport, walking, cycling, public transit, car-sharing and electric vehicles reduce emissions significantly.</p>
<h2>Measure it</h2><p>Use our <a href="../../appliance-energy-cost-calculator/">appliance energy cost calculator</a> to see what individual devices cost you, and the <a href="../../carbon-footprint-calculator/">carbon footprint calculator</a> to compare the big categories.</p>` },
  { slug: 'organise-a-community-cleanup', emoji: '🧤', title: 'How to organise a community cleanup (step by step)', desc: 'From picking a spot to disposing of the bags: a simple plan for a safe and successful beach, park or river cleanup.',
    html: `<p>A cleanup is one of the most visible, rewarding ways to improve a place and bring neighbours together. You do not need an organisation behind you - just a plan.</p>
<h2>Step 1: Choose the place and time</h2><p>Look for a spot that has visible litter and is safe to reach, such as a beach, riverbank, park or neighbourhood street. Pick a daylight time with good weather - for beaches, check the tide chart and aim for low tide.</p>
<h2>Step 2: Get permission and support</h2><p>Contact the local authority, park manager or landowner. Ask whether they provide bags, gloves or pickers and whether they will collect the full bags. Many councils support cleanups and can advise on hazards.</p>
<h2>Step 3: Gather volunteers</h2><p>Share the date on community groups, schools, sports clubs and social media. Ask people to sign up so you know how many to expect. Ask about accessibility needs so everyone can take part.</p>
<!--AD-->
<h2>Step 4: Prepare supplies and safety</h2><p>Use gloves, bags, pickers, a first-aid kit, water and sun protection. Brief everyone on safety: never touch needles, chemicals or large broken glass; stay away from water edges and traffic; and supervise children. Our <a href="../../cleanup-planner/">cleanup planner</a> has a full checklist you can print.</p>
<h2>Step 5: Run the event</h2><p>Welcome people, explain the safety rules, split into zones with team leaders, and sort recyclables if possible. Take photos of before and after. Count or weigh what you collect - noting the top items helps campaign for change.</p>
<h2>Step 6: Dispose and follow up</h2><p>Dispose of waste as agreed. Thank volunteers, share results (without personal details) and report data to citizen-science projects. Schedule the next date while enthusiasm is high.</p>
<h2>Common mistakes</h2><ul><li>Overfilling bags - they become too heavy to lift safely.</li><li>Skipping the safety briefing.</li><li>Forgetting to arrange waste collection.</li><li>Cleaning up sensitive habitats such as dunes or nesting areas without guidance.</li></ul>` },
  { slug: 'composting-basics', emoji: '🌱', title: 'Composting basics: turn scraps into soil', desc: 'What to compost, how to start in a house or apartment, and how to avoid smells and pests.',
    html: `<p>Food scraps and yard waste make up a large share of household garbage. In landfill they rot without oxygen and release methane, a powerful greenhouse gas. Composting turns them into a free soil improver instead.</p>
<h2>The simple recipe: greens plus browns</h2><ul><li><strong>Greens (nitrogen):</strong> fruit and vegetable scraps, coffee grounds, tea bags (without plastic), fresh grass clippings.</li><li><strong>Browns (carbon):</strong> dry leaves, shredded cardboard and paper, straw, sawdust from untreated wood.</li></ul><p>Aim for roughly two to three parts brown to one part green by volume. Keep the pile as damp as a wrung-out sponge and turn it now and then so air gets in.</p>
<h2>What not to add to a home bin</h2><p>Meat, fish, dairy and oily foods (they attract pests and smell), pet waste, diseased plants, glossy paper and anything with plastic. A city green-bin program may accept more - follow your local rules.</p>
<!--AD-->
<h2>Options for every home</h2><ul><li><strong>Backyard bin or pile:</strong> the cheapest option; takes a few months.</li><li><strong>Worm bin (vermicomposting):</strong> works in apartments; red wigglers eat scraps quickly.</li><li><strong>Bokashi bucket:</strong> ferments scraps (including some meat and dairy) indoors; the result is buried or added to a compost pile.</li><li><strong>Municipal green bin or drop-off:</strong> no effort, and the program does the composting.</li></ul>
<h2>Troubleshooting</h2><ul><li><strong>Smelly?</strong> Too wet or too many greens - add dry browns and turn it.</li><li><strong>Not breaking down?</strong> Too dry or too cold - add water and greens; chop material smaller.</li><li><strong>Flies?</strong> Bury food scraps in the middle and cover with browns.</li></ul>
<h2>Using your compost</h2><p>Finished compost is dark, crumbly and smells earthy. Mix it into garden beds and pots, or spread it as a thin layer around plants.</p>` }
];
