const fs = require('fs'), path = require('path');
const D = require('./data'), guides = require('./guides'), E = require('./assets/eco.js'), { card, esc } = require('../../lib/ui');
const CFG = JSON.parse(fs.readFileSync(path.join(__dirname, '..', '..', 'config.json'), 'utf8'));
const site = {
  slug: 'eco-steps', name: 'EcoSteps', tag: 'Small steps for a cleaner planet', emoji: '🌍', accent: '#15803d', accentDark: '#4ade80', soft: '#e5f6ea', softDark: '#10281a',
  desc: 'Practical tools and guides for greener living: carbon footprint calculator, energy cost calculator, recycling sorting guide, plastic-swap checklist and a community cleanup planner.',
  about: 'EcoSteps helps ordinary people take practical, low-cost steps for a cleaner planet - from working out your carbon footprint and cutting plastic to planning a safe community cleanup. Everything is free, runs in your browser and avoids guilt in favour of useful next steps.',
  nav: [['Footprint', 'carbon-footprint-calculator/'], ['Recycling', 'recycling-guide/'], ['Plastic swaps', 'plastic-swap-checklist/'], ['Cleanup planner', 'cleanup-planner/'], ['Guides', 'guides/']], pages: []
};
const tools = [
  ['carbon-footprint-calculator/', '👣', 'Carbon Footprint Calculator', 'Estimate your yearly emissions from driving, home energy, flights and food - and see your biggest slice.'],
  ['appliance-energy-cost-calculator/', '🔌', 'Appliance Energy Cost Calculator', 'What does that device cost to run for a year, and how much CO2 does it cause?'],
  ['recycling-guide/', '♻️', 'Recycling Sorting Guide', 'Where does it go? A searchable guide to common household items.'],
  ['plastic-swap-checklist/', '🛍️', 'Plastic-Free Swap Checklist', 'Track 20 easy swaps that cut single-use plastic. Progress saved on your device.'],
  ['cleanup-planner/', '🧤', 'Community Cleanup Planner', 'A printable checklist for planning a safe, successful beach, park or river cleanup.']
];
const input = (name, label, v, extra = '') => `<div><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="number" inputmode="decimal" min="0" step="any" value="${v}" ${extra}></div>`;
const sel = (name, label, opts, v) => `<div><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${opts.map(([k, l]) => `<option value="${k}"${k === v ? ' selected' : ''}>${esc(l)}</option>`).join('')}</select></div>`;
const faqs = require('./faq');
const mission = CFG.portfolioUrl ? `<p>EcoSteps is part of the Clean Earth Foundation project. <a href="${esc(CFG.portfolioUrl)}" rel="noopener">Learn more</a>.</p>` : '';
site.pages.push({ path: 'index.html', home: true, title: 'EcoSteps', nav: null, desc: site.desc, jsonld: { '@context': 'https://schema.org', '@type': 'WebSite', name: 'EcoSteps', description: site.desc },
  body: ({ rel, ad }) => `<section class="hero"><p class="eyebrow">Practical - free - guilt-free</p><h1>Small steps for a cleaner planet</h1><p class="lead">Measure your footprint, cut plastic, sort recycling correctly and plan a community cleanup. Real tools and plain advice you can use today.</p></section>${ad('top')}
<h2>Tools</h2><div class="grid wide">${tools.map((t) => card(rel + t[0], t[1], t[2], t[3])).join('')}</div>${ad('mid')}
<h2>Guides</h2><div class="grid wide">${guides.map((g) => card(`${rel}guides/${g.slug}/`, g.emoji, g.title, g.desc)).join('')}</div>
<section class="prose full"><h2>Why small steps matter</h2><p>Big environmental problems - plastic in the oceans, rising emissions, wasted energy - are solved by many people changing habits, communities organising, and policy catching up. You do not need to be perfect. You just need a next step: swap one item, fix one leak, join one cleanup. EcoSteps gives you tools to find the steps that matter most for you.</p>${mission}</section>${ad('bottom')}` });
site.pages.push({ path: 'carbon-footprint-calculator/index.html', title: 'Carbon Footprint Calculator', desc: 'Estimate your annual carbon footprint from driving, home energy, flights and diet, with a breakdown of your biggest sources and ideas to cut it.', nav: 'carbon-footprint-calculator/', crumb: ['', ''], short: 'Carbon footprint calculator', scripts: ['assets/eco.js', 'assets/eco-ui.js'], jsonld: require('../../lib/ui').faqLd(faqs.footprint),
  body: ({ rel, ad }) => `<div data-eco="footprint"><h1>Carbon Footprint Calculator</h1><p class="lead">Answer a few quick questions to estimate your yearly greenhouse-gas emissions in tonnes of CO2 equivalent. No sign-up; your answers stay on this device.</p>${ad('top')}
<div class="tool"><form class="panel" id="f" novalidate aria-label="Footprint questions"><div class="fields">${input('carKm', 'Car driving (km per week)', 120)}${input('carL', 'Car fuel use (litres per 100 km)', 8, 'step="0.1"')}${input('transitKm', 'Public transit (km per week)', 20)}${input('kwh', 'Household electricity (kWh per month)', 600)}${input('gasKwh', 'Household natural gas (kWh per month)', 800)}${input('people', 'People in your household', 2, 'min="1"')}${sel('grid', 'Electricity source', Object.entries(E.GRID).map(([k, v]) => [k, v[0]]), 'ca')}${input('short', 'Short return flights per year (under about 3 hours)', 1)}${input('long', 'Long return flights per year', 0)}${sel('diet', 'Diet', Object.entries(E.DIET).map(([k, v]) => [k, v[0]]), 'avg')}<div class="check"><input type="checkbox" id="f-recycle" name="recycle" checked><label for="f-recycle">I recycle and compost most of my waste</label></div></div><button class="btn" type="submit">Calculate</button></form><div class="panel" id="out" aria-live="polite"></div></div></div>
<article class="prose full"><h2>How the estimate works</h2><p>Each part uses a rounded, widely published emission factor: petrol or gasoline at about 2.3 kg CO2 per litre; grid electricity at the intensity of your region; natural gas at about 0.18 kg per kWh; a short return flight at about 0.25 tonnes and a long return flight at about 1.6 tonnes per passenger; and typical yearly food footprints for each diet. Home energy is divided by the number of people in the household.</p>${ad('mid')}<h2>How to read your result</h2><p>The global average is roughly 4.7 tonnes per person per year, and many climate scientists suggest about 2 to 2.5 tonnes per person by 2030 is consistent with limiting warming to 1.5&deg;C. Average per-person figures are much higher in some wealthy countries. The goal is not guilt; it is finding your biggest lever.</p><h2>The biggest levers for most people</h2><ul><li><strong>Transport:</strong> drive less, switch to transit, bike, car-share or an electric vehicle; fly less.</li><li><strong>Home energy:</strong> insulate, use a heat pump, choose a clean electricity supplier. See <a href="${rel}guides/save-energy-at-home/">Save energy at home</a>.</li><li><strong>Food:</strong> eat more plants and waste less food.</li><li><strong>Stuff:</strong> buy less, buy second-hand, repair.</li></ul>${require('../../lib/ui').faqHtml(faqs.footprint)}</article>${ad('bottom')}` });
site.pages.push({ path: 'appliance-energy-cost-calculator/index.html', title: 'Appliance Energy Cost Calculator', desc: 'Find out what any appliance costs to run per month and per year, and the CO2 it produces, from its wattage and hours of use.', nav: null, crumb: ['', ''], short: 'Appliance energy cost', scripts: ['assets/eco.js', 'assets/eco-ui.js'], jsonld: require('../../lib/ui').faqLd(faqs.appliance),
  body: ({ rel, ad }) => `<div data-eco="appliance"><h1>Appliance Energy Cost Calculator</h1><p class="lead">Enter an appliance\'s power in watts, how long it runs and your electricity price. Pick a preset to start.</p>${ad('top')}
<div class="chips" role="group" aria-label="Presets">${[['LED bulb (9 W)', 9, 5], ['Laptop (50 W)', 50, 8, 2], ['Gaming PC (300 W)', 300, 4, 5], ['TV (100 W)', 100, 4, 1], ['Fridge (150 W avg)', 150, 24], ['Space heater (1500 W)', 1500, 4], ['Window A/C (1000 W)', 1000, 6], ['Dryer (3000 W)', 3000, 1], ['Dishwasher (1800 W)', 1800, 1]].map(([l, w, h, s]) => `<button type="button" class="chip" data-w="${w}" data-h="${h}" data-s="${s || 0}">${l}</button>`).join('')}</div>
<div class="tool"><form class="panel" id="f" novalidate>${'<div class="fields">'}${input('watts', 'Power (watts)', 100)}${input('hours', 'Hours used per day', 4, 'max="24" step="0.25"')}${input('days', 'Days used per year', 365, 'max="366"')}${input('price', 'Electricity price per kWh', 0.15, 'step="0.001"')}${input('standby', 'Standby power when off (watts)', 0, 'step="0.1"')}${sel('grid', 'Electricity source (for CO2)', Object.entries(E.GRID).map(([k, v]) => [k, v[0]]), 'world')}<div><label for="f-cur">Currency symbol</label><input id="f-cur" name="cur" type="text" value="$" maxlength="3"></div></div><button class="btn" type="submit">Calculate</button></form><div class="panel" id="out" aria-live="polite"></div></div></div>
<article class="prose full"><h2>How it works</h2><p>Energy use in kilowatt-hours (kWh) is power in kilowatts multiplied by hours of use. A 100 W device running 4 hours a day for a year uses 100 W &times; 4 h &times; 365 / 1000 = 146 kWh. Multiply by your price per kWh (find it on your bill) for the cost.</p>${ad('mid')}<h2>Where to find the wattage</h2><p>Look on the label or power adapter, or in the manual. If it lists amps and volts, multiply them (watts = volts &times; amps). A plug-in energy meter can measure actual use. Appliances with motors or heating elements cycle on and off, so real use may be lower than the rated power.</p><h2>Biggest savings</h2><ul><li>Heating and cooling devices and electric water heaters are usually the largest.</li><li>Replace old bulbs with LEDs.</li><li>Use a power strip to switch off devices with standby drain.</li></ul>${require('../../lib/ui').faqHtml(faqs.appliance)}</article>${ad('bottom')}` });
site.pages.push({ path: 'recycling-guide/index.html', title: 'Recycling Sorting Guide: Where Does It Go?', desc: `Searchable guide to ${D.recycling.length} common household items: recycling, compost, garbage, drop-off or hazardous waste.`, nav: 'recycling-guide/', crumb: ['', ''], short: 'Recycling guide', scripts: ['assets/eco-ui.js'],
  body: ({ ad }) => `<div data-eco="recycle"><h1>Recycling sorting guide</h1><p class="lead">Where does it go? Search for an item. Rules vary by city, so treat this as general guidance and check your local program.</p>${ad('top')}<div class="panel"><label for="rq">Search items</label><input id="rq" type="search" placeholder="battery, pizza box, plastic bag..." autocomplete="off"></div><div class="table-wrap" style="margin-top:1rem"><table id="rt"><thead><tr><th>Item</th><th>Usually goes to</th><th>Tip</th></tr></thead><tbody>${D.recycling.map(([a, b, c]) => `<tr data-q="${esc((a + ' ' + b + ' ' + c).toLowerCase())}"><td><strong>${esc(a)}</strong></td><td>${esc(b)}</td><td>${esc(c)}</td></tr>`).join('')}</tbody></table></div><p class="empty" id="rn" hidden>No item matches - when in doubt, check your local waste website.</p></div>${ad('mid')}
<article class="prose full"><h2>Recycling rules of thumb</h2><ul><li><strong>Empty, clean, dry:</strong> food residue contaminates paper and other recyclables.</li><li><strong>Do not bag your recycling</strong> unless your program asks you to; loose items are sorted more easily.</li><li><strong>"When in doubt, find out":</strong> a wrong item (a "wishcycled" plastic bag, say) can spoil a whole load.</li><li><strong>Reduce and reuse come first.</strong> Recycling is the last resort, not the first.</li></ul></article>${ad('bottom')}` });
const checklist = (key, title, intro, items, ad, extra = '') => `<div data-eco="checklist" data-key="${key}"><h1>${title}</h1><p class="lead">${intro}</p>${ad('top')}<div class="panel"><div class="row"><strong id="prog" role="status"></strong><button type="button" class="btn small ghost" id="reset">Reset</button><button type="button" class="btn small ghost" id="print">Print</button></div><div class="progress" aria-hidden="true"><i id="progbar"></i></div>${items}</div></div>${extra}`;
const todo = (arr, pre) => `<ul class="todo">${arr.map(([t, s], i) => `<li><input type="checkbox" id="${pre}${i}" data-i="${pre}${i}"><label for="${pre}${i}">${esc(t)}<small class="muted">${esc(s)}</small></label></li>`).join('')}</ul>`;
site.pages.push({ path: 'plastic-swap-checklist/index.html', title: 'Plastic-Free Swap Checklist: 20 Easy Swaps', desc: 'Tick off 20 simple swaps that cut single-use plastic. Your progress is saved privately on your device.', nav: 'plastic-swap-checklist/', crumb: ['', ''], short: 'Plastic swap checklist', scripts: ['assets/eco-ui.js'],
  body: ({ rel, ad }) => checklist('swaps', 'Plastic-free swap checklist', 'Tick the swaps you have made. Start with two or three that fit your life - consistency beats perfection.', todo(D.swaps, 's'), ad, `${ad('mid')}<article class="prose full"><h2>Make swaps without waste</h2><p>Use up what you already own before replacing it, and choose durable items you will actually use. Read more in <a href="${rel}guides/reduce-plastic-at-home/">15 easy ways to use less plastic at home</a> and <a href="${rel}guides/ocean-plastic-explained/">Ocean plastic explained</a>.</p></article>${ad('bottom')}`) });
site.pages.push({ path: 'cleanup-planner/index.html', title: 'Community Cleanup Planner & Checklist', desc: 'A free printable checklist for planning a safe beach, park or river cleanup: permissions, supplies, safety briefing, the day itself and follow-up.', nav: 'cleanup-planner/', crumb: ['', ''], short: 'Cleanup planner', scripts: ['assets/eco-ui.js'],
  body: ({ rel, ad }) => checklist('cleanup', 'Community cleanup planner', 'Work through each stage. Tick items as you go (saved on your device) and print the list for the day.', D.cleanup.map(([h, a], j) => `<h2>${esc(h)}</h2>${todo(a, 'c' + j + '_')}`).join(''), ad, `${ad('mid')}<article class="prose full"><h2>Need more detail?</h2><p>Read our step-by-step guide: <a href="${rel}guides/organise-a-community-cleanup/">How to organise a community cleanup</a>. Always follow local rules and get permission before organising on public or private land, and never handle hazardous items.</p></article>${ad('bottom')}`) });
site.pages.push({ path: 'guides/index.html', title: 'Eco Guides', desc: 'Practical guides: reduce plastic, save energy, understand ocean plastic, organise a cleanup and start composting.', nav: 'guides/', crumb: ['', ''], short: 'Guides',
  body: ({ rel, ad }) => `<h1>Guides</h1><p class="lead">Straightforward advice for greener living.</p>${ad('top')}<div class="grid wide">${guides.map((g) => card(`${rel}guides/${g.slug}/`, g.emoji, g.title, g.desc)).join('')}</div>${ad('bottom')}` });
for (const g of guides) site.pages.push({ path: `guides/${g.slug}/index.html`, title: g.title, desc: g.desc, nav: 'guides/', crumb: ['Guides', 'guides/'], short: g.title, jsonld: { '@context': 'https://schema.org', '@type': 'Article', headline: g.title, description: g.desc, dateModified: new Date().toISOString().slice(0, 10) },
  body: ({ rel, ad }) => `<article class="prose"><p class="eyebrow">Guide</p><h1>${esc(g.title)}</h1>${g.html.split('<!--AD-->')[0]}${ad('mid')}${g.html.split('<!--AD-->')[1] || ''}</article><section><h2>Keep reading</h2><div class="grid">${guides.filter((x) => x !== g).slice(0, 3).map((x) => card(`${rel}guides/${x.slug}/`, x.emoji, x.title, x.desc)).join('')}</div></section>${ad('bottom')}` });
module.exports = site;
