// Original explanatory content for each calculator page (helps visitors and gives every page real substance).
module.exports = {
  mortgage: {
    h1: 'Mortgage & Loan Payment Calculator',
    intro: 'Enter the amount you want to borrow, the interest rate and how long you will take to pay it back. You get the regular monthly payment, the total interest over the life of the loan and a year-by-year balance table. Add an extra monthly payment to see how much interest and time you could save.',
    about: ['<h2>How the payment is worked out</h2><p>A standard amortizing loan has a fixed payment. Each month, interest is charged on whatever you still owe, and the rest of the payment reduces the balance. Early on most of the payment is interest; later most of it is principal. The calculator uses the usual formula <code>payment = P &times; r / (1 &minus; (1 + r)<sup>&minus;n</sup>)</code>, where <code>P</code> is the amount borrowed, <code>r</code> the interest rate per month and <code>n</code> the number of monthly payments.</p>',
      '<h2>Canadian vs US mortgages</h2><p>In the US, interest on a mortgage is normally compounded monthly. By law, fixed-rate Canadian mortgages compound semi-annually, which makes the monthly payment very slightly lower for the same quoted rate. Use the compounding menu to pick the style that matches your lender; for car loans and personal loans, monthly is the usual choice.</p>',
      '<h2>Why extra payments are powerful</h2><p>Every extra dollar you pay goes straight to principal, so you stop paying interest on it for the rest of the loan. Even a modest extra amount each month can cut years from a 25-year mortgage. Try adding $100 or $200 above and watch the "Interest saved" and "Time saved" figures change.</p>',
      '<h2>What is not included</h2><p>Property tax, home insurance, mortgage default insurance, condo fees and lender fees are not part of this number. Your real monthly housing cost will be higher. Always confirm figures with your lender.</p>'],
    faq: [['What is a good interest rate?', 'It depends on the market, your credit, the loan type and the term. Compare offers from several lenders on the same day and the same term.'], ['Should I choose a shorter term?', 'A shorter term means higher payments but far less total interest. Pick the shortest term whose payment you can comfortably afford with some room for surprises.'], ['Does this work for car loans?', 'Yes. Set the amount, rate and term in years (for example 5) and keep compounding on monthly.'], ['Are the results exact?', 'They are accurate estimates of the standard formula. Your lender may round payments, charge fees or use a different payment schedule.']],
    related: ['compound', 'salary', 'percent'] },
  tip: {
    h1: 'Tip & Bill Split Calculator',
    intro: 'Type the bill, pick a tip percentage and choose how many people are sharing. You will see the tip, the total and what each person owes. Tap a preset to try 10%, 15%, 18%, 20% or 25% in one click.',
    about: ['<h2>Tipping at a glance</h2><p>Customs differ a lot. In the United States and Canada, 15-20% of the pre-tax bill is typical in sit-down restaurants, and many people tip a little more for great service. In much of Europe a service charge is already included and rounding up or leaving a few coins is common. In Japan tipping is generally not expected. When in doubt, check the receipt: some places already add a gratuity for large groups.</p>',
      '<h2>Tip on the pre-tax amount?</h2><p>Many people calculate the tip on the bill before sales tax, others on the total. Both are fine; the difference is small. Enter whichever amount you prefer in the bill box.</p>',
      '<h2>Splitting fairly</h2><p>The calculator divides the total evenly. If people ordered very different amounts, run the numbers for each person separately with one person per calculation. The "round up" option makes each share a whole number, which is handy when paying in cash.</p>'],
    faq: [['How much should I tip?', 'In North America 18-20% is common for good table service. Use the preset buttons to compare.'], ['Do I tip on the tax?', 'It is a personal choice; many tip on the pre-tax subtotal.'], ['Can I split unevenly?', 'Calculate each person\'s own items separately, then add the tip share proportionally.']],
    related: ['percent', 'discount', 'fuel'] },
  percent: {
    h1: 'Percentage Calculator',
    intro: 'Five of the percentage questions people ask most, in one place: what is X% of Y, X is what percent of Y, percentage change, and increase or decrease a number by a percent.',
    about: ['<h2>The formulas</h2><ul><li><strong>X% of Y</strong> = X &divide; 100 &times; Y. Example: 15% of 200 is 30.</li><li><strong>X is what % of Y</strong> = X &divide; Y &times; 100. Example: 30 is 15% of 200.</li><li><strong>Percentage change</strong> = (new &minus; old) &divide; |old| &times; 100. Going from 50 to 75 is +50%.</li><li><strong>Increase by X%</strong> = Y &times; (1 + X/100). <strong>Decrease</strong> = Y &times; (1 &minus; X/100).</li></ul>',
      '<h2>Percent change is not symmetrical</h2><p>If a price rises 50% and then falls 50%, you do not return to the start: 100 becomes 150 and then 75. A fall of 33.3% is needed to undo a 50% rise. This is why percent change always depends on which number you start from.</p>',
      '<h2>Percentage points vs percent</h2><p>If an interest rate goes from 4% to 5%, it rose by one <em>percentage point</em> but by 25 <em>percent</em> relative to the old rate. News stories often mix these up, so check which one is meant.</p>'],
    faq: [['How do I calculate a discount?', 'Use "Decrease Y by X%" - or try the Discount & Sales Tax calculator.'], ['What if the starting value is negative?', 'Percent change uses the absolute value of the starting number so the direction stays meaningful.'], ['How many decimals are shown?', 'Up to six, with trailing zeros removed.']],
    related: ['discount', 'tip', 'compound'] },
  bmi: {
    h1: 'BMI Calculator',
    intro: 'Body mass index (BMI) compares your weight to your height. Enter your measurements in metric or imperial units to see your BMI, the adult category and the weight range that corresponds to the "healthy" BMI band for your height.',
    about: ['<h2>How BMI is calculated</h2><p>BMI = weight in kilograms &divide; (height in metres)<sup>2</sup>. In imperial units the calculator first converts pounds, feet and inches to kilograms and metres, so both modes give the same answer for the same person.</p>',
      '<h2>WHO adult categories</h2><table><thead><tr><th>BMI</th><th>Category</th></tr></thead><tbody><tr><td>Below 18.5</td><td>Underweight</td></tr><tr><td>18.5 - 24.9</td><td>Healthy range</td></tr><tr><td>25 - 29.9</td><td>Overweight</td></tr><tr><td>30 and above</td><td>Obesity range</td></tr></tbody></table>',
      '<h2>What BMI cannot tell you</h2><p>BMI is a quick screening number, not a measure of health. It does not know how much of your weight is muscle, bone or fat, nor where fat is stored. Athletes can have a high BMI and be healthy; some people with a "normal" BMI still have health risks. It is also designed for adults - not for children, teens (who use growth charts), or during pregnancy. For personal advice, speak to a doctor or dietitian.</p>'],
    faq: [['Is BMI accurate?', 'It is a rough population-level tool. Use it as one data point, not a verdict.'], ['Does it work for children?', 'No. Children and teens are assessed with age- and sex-specific growth charts.'], ['Do different countries use different cut-offs?', 'Some Asian health bodies suggest lower cut-offs for risk. This calculator uses the WHO adult bands.']],
    related: ['percent', 'units', 'age'] },
  compound: {
    h1: 'Compound Interest & Savings Calculator',
    intro: 'Compound interest means you earn interest on your interest. Enter a starting balance, a monthly deposit, an annual return and a time horizon to see how far steady saving can take you, with a year-by-year table.',
    about: ['<h2>The power of time</h2><p>Growth accelerates because each year\'s interest is added to the balance that earns the next year\'s interest. That is why starting early matters more than starting big: money invested for 30 years has far longer to compound than money invested for 10.</p>',
      '<h2>How this calculator works</h2><p>It converts the annual return and compounding frequency into an equivalent monthly rate, then, month by month, grows the balance and adds your deposit. Deposits are assumed to be made at the end of each month.</p>',
      '<h2>The rule of 72</h2><p>A quick mental shortcut: divide 72 by the annual percentage return to estimate how many years it takes money to double. At 6% it is about 12 years; at 9% about 8 years.</p>',
      '<h2>Be realistic</h2><p>Investment returns vary year to year and are never guaranteed; savings account rates change. Fees, inflation and taxes reduce what you keep. Treat the result as an illustration, not a forecast.</p>'],
    faq: [['What return should I assume?', 'Savings accounts and bonds pay less than stocks have historically, but stocks can fall sharply. Try several rates, including a pessimistic one.'], ['Does it include inflation?', 'No. To see value in today\'s money, subtract expected inflation from the return rate.'], ['Is compounding daily much better than monthly?', 'Only slightly. The rate and time matter far more than the frequency.']],
    related: ['mortgage', 'salary', 'percent'] },
  units: {
    h1: 'Unit Converter',
    intro: 'Convert between metric and imperial units instantly: length, weight, volume, speed, area, temperature and time. Every other unit of the same type is shown too, so you can see the whole picture at once.',
    about: ['<h2>Common conversions to remember</h2><ul><li>1 inch = 2.54 centimetres exactly</li><li>1 mile = 1.609344 kilometres</li><li>1 kilogram &asymp; 2.2046 pounds</li><li>1 US gallon = 3.785 litres; 1 UK (imperial) gallon = 4.546 litres</li><li>0&deg;C = 32&deg;F; 100&deg;C = 212&deg;F; 0 K = &minus;273.15&deg;C</li></ul>',
      '<h2>US vs UK gallons and cups</h2><p>The US and UK gallon are different sizes, which causes real confusion with fuel economy (mpg). This tool lists both so you can pick the right one. US cups here are the legal US cup of 236.588 ml.</p>',
      '<h2>Temperature is different</h2><p>Temperature scales have different zero points, so converting is not just multiplying. Fahrenheit = Celsius &times; 9/5 + 32. Kelvin = Celsius + 273.15.</p>'],
    faq: [['How precise is it?', 'Conversion factors are the exact or internationally accepted values and results show up to 8 significant decimals.'], ['Why do some results show many digits?', 'Small units like millimetres produce large numbers. Use the table to pick the unit that suits you.'], ['Can I swap from and to?', 'Yes, press the swap button.']],
    related: ['bmi', 'fuel', 'percent'] },
  dates: {
    h1: 'Age & Date Difference Calculator',
    intro: 'Find your exact age or the time between any two dates in years, months and days, plus total days, weeks and Monday-to-Friday working days. Leave the end date empty to use today.',
    about: ['<h2>How the difference is counted</h2><p>The calculator counts whole years first, then whole months, then the remaining days, borrowing from the previous month when needed (so 28 Feb to 1 Mar in a leap year is 2 days). Total days are the plain calendar days between the dates.</p>',
      '<h2>Working days</h2><p>Working days count Monday to Friday between the dates (the start day is included, the end day is not). Public holidays are not removed because they differ by country and region - subtract them yourself if needed.</p>',
      '<h2>Uses</h2><p>Check an exact age for a form, count the days until a deadline, work out how long you have been in a job, plan a countdown to a trip, or measure the length of a project.</p>'],
    faq: [['Does it handle leap years?', 'Yes, it uses real calendar dates.'], ['If the end date is before the start date?', 'The two dates are swapped and the result says so.'], ['What does "approx." mean for months?', 'Months have different lengths, so total months are whole calendar months only.']],
    related: ['salary', 'units', 'compound'] },
  salary: {
    h1: 'Hourly to Salary Calculator',
    intro: 'Turn an hourly wage into an annual salary - or an annual salary into an hourly rate - and see the same pay as monthly, bi-weekly, weekly and daily amounts. Adjust hours per week and paid weeks to match your job.',
    about: ['<h2>The simple math</h2><p>Annual pay = hourly rate &times; hours per week &times; paid weeks per year. A $28 hourly wage at 40 hours a week for 52 weeks is $58,240 a year, or about $4,853 a month.</p>',
      '<h2>Gross vs take-home</h2><p>These figures are before tax, pension, insurance and other deductions. Your take-home (net) pay will be lower and depends on where you live. Use your government\'s official payroll or tax calculator for net pay.</p>',
      '<h2>Part-time, unpaid weeks and overtime</h2><p>If you take unpaid weeks off, lower the "paid weeks" box. For part-time work, change the hours. Overtime is not included, because the multiplier differs between countries and contracts.</p>'],
    faq: [['How many working hours are in a year?', 'A full-time schedule of 40 hours for 52 weeks is 2,080 hours (2,000 if you count two weeks unpaid).'], ['What about salary to hourly?', 'Choose "Annual salary" in the menu: the calculator divides by hours worked in the year.'], ['Is bi-weekly the same as twice a month?', 'No. Bi-weekly means every two weeks (26 payments), semi-monthly means twice a month (24).']],
    related: ['percent', 'compound', 'mortgage'] },
  fuel: {
    h1: 'Fuel Cost & Trip Calculator',
    intro: 'Planning a road trip? Enter the distance, your vehicle\'s fuel use and the current fuel price to see the fuel cost, the cost per kilometre or mile, and each person\'s share if you split the cost.',
    about: ['<h2>Fuel economy units</h2><p>Metric countries use litres per 100 km (lower is better): 8 L/100 km means the car uses 8 litres to go 100 km. In the US, mpg (miles per gallon) is used and higher is better. This tool lets you pick either and converts nothing behind your back - just choose your units.</p>',
      '<h2>Ways to spend less on fuel</h2><ul><li>Keep tyres at the recommended pressure.</li><li>Drive smoothly - hard acceleration and braking waste fuel.</li><li>Slow down on the highway: air resistance rises quickly with speed.</li><li>Remove roof racks and unneeded weight.</li><li>Combine errands into one trip, and share rides when you can.</li></ul>',
      '<h2>Trip costs beyond fuel</h2><p>This number covers fuel only. Real driving costs also include tolls, parking, maintenance and depreciation. Use a longer-term cost per kilometre if you want to compare driving with transit or flying.</p>'],
    faq: [['Where do I find my fuel use?', 'Check your trip computer, owner\'s manual or divide litres filled by kilometres driven, then multiply by 100.'], ['Does it handle round trips?', 'Tick "Round trip" to double the distance.'], ['Which currency does it use?', 'Pick any currency in the box above the calculator. It only changes the symbol.']],
    related: ['units', 'tip', 'discount'] },
  discount: {
    h1: 'Discount & Sales Tax Calculator',
    intro: 'See what an item really costs after a sale: enter the price, the percent off and the sales tax. Or switch the mode to remove tax from a total and find the price before tax.',
    about: ['<h2>Order matters (a little)</h2><p>In most places sales tax is charged on the discounted price, so a discount saves you tax as well. That is how this calculator works. A few stores apply a coupon after tax; check your receipt if the number differs.</p>',
      '<h2>Stacked discounts</h2><p>Two discounts of 20% and 10% are not 30% off. The second applies to an already-reduced price, giving 28% off in total (0.8 &times; 0.9 = 0.72). Run the calculator twice to see it, using the first result as the new price.</p>',
      '<h2>Removing tax</h2><p>To find the pre-tax price from a total, divide by 1 + the tax rate. For a $113 total with 13% tax, the pre-tax price is $100 and the tax is $13. Switch the menu to "Remove tax from a total".</p>'],
    faq: [['Is 50% off then 20% off the same as 70% off?', 'No, it is 60% off. 0.5 &times; 0.8 = 0.4 of the original price.'], ['What tax rate should I use?', 'Use your local rate - for example combined GST/HST/PST in Canada, or state plus local sales tax in the US.'], ['Can I enter a price with tax included?', 'Yes - switch to "Remove tax from a total".']],
    related: ['percent', 'tip', 'compound'] }
};
