module.exports = [
  { slug: 'pay-off-your-mortgage-faster', emoji: '🏠', title: 'How to pay off your mortgage faster', desc: 'Five practical ways to cut years and thousands in interest from a mortgage - with the maths behind each.', try: 'mortgage',
    html: `<p>A mortgage is usually the biggest debt a household carries, and the interest on it can rival the price of the house itself. The good news is that small, steady changes can remove years from the schedule. Here is how the main strategies work.</p>
<h2>1. Add a small extra payment every month</h2><p>Extra money goes straight to principal. On a $350,000 loan at 5.25% over 25 years, an extra $200 a month shortens the mortgage by roughly three and a half years and saves well over $40,000 in interest. The earlier in the loan you do it, the larger the effect, because interest is highest at the start.</p>
<h2>2. Switch to accelerated bi-weekly payments</h2><p>Paying half the monthly amount every two weeks gives 26 half-payments a year - the same as 13 full monthly payments instead of 12. That one extra payment a year is quietly applied to principal. Ask your lender whether their "accelerated" option is truly half the monthly payment, because some are not.</p>
<!--AD-->
<h2>3. Use lump sums wisely</h2><p>Tax refunds, bonuses and gifts can be used for prepayment. Many lenders allow annual lump-sum payments of 10-20% of the original balance without a penalty. Read your contract: some loans charge a prepayment penalty, especially in the early years or on fixed rates.</p>
<h2>4. Choose a shorter amortization when you can afford it</h2><p>A 20-year mortgage costs more per month than a 30-year one but far less in total interest. If you cannot commit to the higher payment, keep the longer term and make voluntary extra payments instead - you keep the flexibility to stop if money gets tight.</p>
<h2>5. Compare rates when you renew</h2><p>A difference of half a percentage point sounds small, but over a large balance it adds up to thousands of dollars. When your term ends, shop around, and ask your current lender to match the best offer.</p>
<h2>Before you prepay: check the big picture</h2><p>Paying down a mortgage is a guaranteed, risk-free return equal to your interest rate. But keep an emergency fund first, clear higher-interest debt such as credit cards, and think about retirement savings that come with an employer match. A balanced plan beats an all-in plan.</p>
<p class="footnote">This guide is general information, not financial advice. Check your own loan terms and talk to a qualified adviser.</p>` },
  { slug: 'tipping-around-the-world', emoji: '🍽️', title: 'Tipping around the world: a quick guide', desc: 'How much to tip in North America, Europe, Asia and elsewhere - and when not to tip at all.', try: 'tip',
    html: `<p>Tipping rules change from one country to the next, and getting it wrong can range from awkward to mildly offensive. This guide explains common customs. Rules also change over time, so when in doubt, check the bill or ask a local.</p>
<h2>United States and Canada</h2><p>Tipping is expected. For table service, 15-20% of the pre-tax bill is standard, and 18-20% or more is common for good service. Bartenders usually get $1-2 per drink, taxi and rideshare drivers 15-20%, hairdressers 15-20%, and hotel housekeeping $3-5 per night. Tipping is built into servers' wages, which is why it matters so much.</p>
<h2>United Kingdom and Ireland</h2><p>Many restaurants add a 10-12.5% service charge. If it is on the bill, no more is needed; if not, 10-12% is polite. Tipping in pubs is not expected - you can offer to "have one yourself" to the bartender. Round up taxi fares.</p>
<!--AD-->
<h2>Continental Europe</h2><p>Service is often included. Leaving small change or rounding up (5-10%) is appreciated for good service in France, Germany, Italy or Spain, but not required. In Germany it is customary to tell the server the total you want to pay when you hand over the cash, rather than leaving money on the table.</p>
<h2>Japan, South Korea and China</h2><p>Tipping is generally not expected and can cause confusion. Excellent service is part of the culture, and attempting to leave money may be politely refused. Some high-end hotels and tour guides in China accept it.</p>
<h2>Australia and New Zealand</h2><p>Staff are paid full wages. Tips are welcome for outstanding service but not expected; 10% in a fine-dining restaurant is generous.</p>
<h2>Latin America, the Caribbean and the Middle East</h2><p>Practices vary widely. A 10% service charge is often added automatically; check the bill. Tips for porters, guides and drivers are customary. Carry small notes in local currency.</p>
<h2>Practical tips</h2><ul><li>Look for "service included" on the bill before adding anything.</li><li>Tip in cash where the card machine does not allow tips to reach staff.</li><li>Calculate on the pre-tax amount if you like; both are acceptable.</li><li>If service was bad, speak to the manager rather than leave nothing without explanation.</li></ul>
<p class="footnote">Customs are general guidance and may vary by region, venue and over time.</p>` },
  { slug: 'compound-interest-explained', emoji: '📈', title: 'Compound interest explained simply', desc: 'What compound interest is, why starting early matters, the rule of 72, and how fees and inflation change the picture.', try: 'compound',
    html: `<p>Albert Einstein is often credited with calling compound interest the eighth wonder of the world - a quote nobody can actually source - but the idea is truly powerful. It is what makes patient saving work.</p>
<h2>Simple vs compound</h2><p>With simple interest, you earn interest only on your original amount. With compound interest, you earn interest on your original amount <em>and</em> on the interest already earned. $1,000 at 7% simple interest earns $70 every year forever. At 7% compounded annually it earns $70 in year one, $74.90 in year two, $80.14 in year three, and keeps growing. After 30 years the simple balance is $3,100; the compounded one is about $7,612.</p>
<h2>Why starting early beats starting big</h2><p>Imagine two savers who both earn 6% a year. Ava invests $200 a month from age 25 to 35 (ten years) and then stops. Ben waits until 35 and invests $200 a month until 65 (thirty years). Despite putting in three times as much, Ben may end up with less than Ava, because her money had ten extra years to compound. Time is the most valuable ingredient.</p>
<!--AD-->
<h2>The rule of 72</h2><p>Divide 72 by the annual return to estimate the years to double your money. At 4% it takes about 18 years, at 6% about 12, at 8% about 9. It works in reverse for debt: a credit card charging 24% doubles what you owe in about three years if you only pay the minimum.</p>
<h2>What eats your returns</h2><ul><li><strong>Fees:</strong> A 2% annual fund fee on a 7% return leaves 5% - that can cost you a third of your final balance over decades.</li><li><strong>Inflation:</strong> If prices rise 3% a year, a 5% return is really about 2% in buying power.</li><li><strong>Taxes:</strong> Tax-advantaged accounts (like a TFSA, RRSP, 401(k), ISA or IRA, depending on your country) can help you keep more.</li></ul>
<h2>Making it work for you</h2><p>Automate a deposit on payday so you never have to decide. Raise it whenever your income rises. Do not panic-sell when markets fall - historically, time in the market has mattered more than timing. Use the calculator to compare scenarios and see how a small change in rate or deposit transforms the result.</p>
<p class="footnote">General education, not financial advice. Investment returns are not guaranteed.</p>` },
  { slug: 'percentages-made-easy', emoji: '％', title: 'Percentages made easy: mental maths tricks', desc: 'Quick ways to work out 10%, 15%, 20%, sale prices and percentage change in your head.', try: 'percent',
    html: `<p>You do not need a calculator for most everyday percentages. A handful of tricks gets you close enough to decide quickly, and the calculator can confirm the exact answer.</p>
<h2>Find 10% first</h2><p>10% is just moving the decimal point one place left: 10% of 86.40 is 8.64. From 10% you can build almost anything: 20% is double it, 5% is half of it, 15% is 10% plus 5%, 1% is moving two places.</p>
<h2>Work out a tip in seconds</h2><p>For an $86.40 bill: 10% is $8.64; double it for 20% = $17.28. For 15%, add half of the 10% ($4.32) to get $12.96.</p>
<!--AD-->
<h2>Sale prices</h2><p>"30% off $120": find 10% ($12), triple it ($36), subtract: $84. Or think of it as paying 70%: 7 x $12 = $84. Thinking in terms of what you pay (70%) is usually faster than thinking about what you save.</p>
<h2>Flip the numbers</h2><p>x% of y equals y% of x. So 8% of 50 is the same as 50% of 8 - which is 4. Pick the easier direction.</p>
<h2>Percentage change</h2><p>Change = (new - old) / old. From 40 to 50 is a rise of 10 on a base of 40, which is 25%. Remember the base is always the <em>old</em> number, so a rise from 40 to 50 (+25%) is not undone by a fall from 50 to 40 (-20%).</p>
<h2>Common traps</h2><ul><li>Two discounts of 20% do not make 40%; they make 36%.</li><li>A "50% increase" followed by a "50% decrease" ends up 25% lower than you started.</li><li>Percentage points and percent are different things: going from 3% to 4% is +1 point but +33% in relative terms.</li></ul>
<p class="footnote">Practice with the percentage calculator until these feel natural.</p>` }
];
