#!/usr/bin/env node
// Static site generator for the five sites.  node build.js [slug...]   ->  dist/<slug>/
// Environment: ADSENSE_CLIENT (ca-pub-...), ADSENSE_SLOT_TOP/MID/BOTTOM override config.json. BASE_<SLUG> overrides a site's public URL.
const fs = require('fs'), path = require('path');
const { render } = require('./lib/layout'), legal = require('./lib/legal');
const ROOT = __dirname, CFG = JSON.parse(fs.readFileSync(path.join(ROOT, 'config.json'), 'utf8'));
const only = process.argv.slice(2);
const client = process.env.ADSENSE_CLIENT || CFG.adsenseClient || '';
const slots = { top: process.env.ADSENSE_SLOT_TOP || CFG.slots.top, mid: process.env.ADSENSE_SLOT_MID || CFG.slots.mid, bottom: process.env.ADSENSE_SLOT_BOTTOM || CFG.slots.bottom };
const rm = (d) => { try { fs.rmSync(d, { recursive: true, force: true }); } catch (e) { /* ignore */ } };
const put = (f, t) => { fs.mkdirSync(path.dirname(f), { recursive: true }); fs.writeFileSync(f, t); };
function copyDir(a, b) { if (!fs.existsSync(a)) return; fs.mkdirSync(b, { recursive: true }); for (const e of fs.readdirSync(a, { withFileTypes: true })) { const s = path.join(a, e.name), d = path.join(b, e.name); if (e.isDirectory()) copyDir(s, d); else fs.copyFileSync(s, d); } }
const slugs = Object.keys(CFG.sites).filter((s) => !only.length || only.includes(s));
const report = [];
for (const slug of slugs) {
  const site = require(path.join(ROOT, 'src', slug, 'site.js'));
  const baseUrl = process.env['BASE_' + slug.toUpperCase().replace(/-/g, '_')] || CFG.sites[slug].url;
  site.others = Object.keys(CFG.sites).filter((s) => s !== slug).map((s) => ({ name: CFG.sites[s].name, url: (process.env['BASE_' + s.toUpperCase().replace(/-/g, '_')] || CFG.sites[s].url) }));
  site.issues = site.issues || `https://github.com/${CFG.githubUser}/${slug}/issues`;
  const out = path.join(ROOT, 'dist', slug); rm(out); fs.mkdirSync(out, { recursive: true });
  const pages = [...site.pages, ...legal(site)];
  const seen = new Set();
  for (const p of pages) { if (seen.has(p.path)) throw new Error(slug + ': duplicate page ' + p.path); seen.add(p.path); put(path.join(out, p.path), render(site, p, { baseUrl })); }
  { const b = baseUrl.replace(/\/$/, '') + '/'; const html = render(site, { path: '404.html', title: 'Page not found', desc: 'Page not found', noindex: true, body: '<div class="hero"><h1>Page not found</h1><p class="lead">That page does not exist or has moved. Try the home page.</p><p><a class="btn" href="index.html">Go to the home page</a></p></div>', scripts: [] }, { baseUrl: '' }).replace(/(href|src)="(?!https?:|#|data:|mailto:)/g, '$1="' + b); put(path.join(out, '404.html'), html); }
  copyDir(path.join(ROOT, 'src', 'common'), path.join(out, 'assets'));
  copyDir(path.join(ROOT, 'src', slug, 'assets'), path.join(out, 'assets'));
  copyDir(path.join(ROOT, 'src', slug, 'data'), path.join(out, 'data'));
  put(path.join(out, 'assets', 'site-config.js'), `window.SITE_CONFIG=${JSON.stringify({ site: slug, adsenseClient: client, slots, baseUrl })};\n`);
  const base = baseUrl.replace(/\/$/, '');
  const today = new Date().toISOString().slice(0, 10);
  put(path.join(out, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.filter((p) => !p.noindex).map((p) => `<url><loc>${base}/${p.path.replace(/index\.html$/, '')}</loc><lastmod>${today}</lastmod></url>`).join('\n')}\n</urlset>\n`);
  put(path.join(out, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
  if (client) put(path.join(out, 'ads.txt'), `google.com, ${client.replace(/^ca-/, '')}, DIRECT, f08c47fec0942fa0\n`);
  put(path.join(out, '.nojekyll'), '');
  put(path.join(out, 'README.md'), `# ${site.name}\n\n${site.desc}\n\nStatic site, no build step needed to host: publish this folder (GitHub Pages / Netlify / any static host).\nGenerated by the Masons-coding site engine.\n`);
  report.push(`${slug}: ${pages.length} pages`);
}
console.log(report.join('\n'));
