const tools = require('./tools-data'), status = require('./status'), { faqHtml, faqLd, card, esc } = require('../../lib/ui');
const site = {
  slug: 'dev-pocket', name: 'DevPocket', tag: 'Free developer tools that run in your browser', emoji: '🧰', accent: '#4f46e5', accentDark: '#a5b4fc', soft: '#eceafd', softDark: '#1e1b3f',
  desc: 'Free online developer tools: JSON formatter, Base64, URL encoder, UUID and password generators, hashes, regex tester, timestamp and colour converters. Private - runs in your browser.',
  about: 'DevPocket is a pocket-sized toolbox for developers, students and anyone who works with data: format JSON, test a regex, convert a timestamp, generate a secure password. Every tool runs entirely in your browser, so what you paste never leaves your device.',
  nav: [['Tools', 'index.html#tools'], ['HTTP status codes', 'http-status-codes/'], ['JSON', 'json-formatter/'], ['Regex', 'regex-tester/'], ['Passwords', 'password-generator/']], pages: []
};
const bySlug = (id) => tools.find((t) => t.id === id);
site.pages.push({ path: 'index.html', home: true, title: 'DevPocket', nav: 'index.html#tools', desc: site.desc, scripts: ['assets/home.js'], jsonld: { '@context': 'https://schema.org', '@type': 'WebSite', name: 'DevPocket', description: site.desc },
  body: ({ rel, ad }) => `<section class="hero"><p class="eyebrow">Private - fast - free</p><h1>Developer tools that stay in your browser</h1><p class="lead">Format JSON, test regular expressions, convert timestamps and colours, generate UUIDs and passwords. No sign-up, no uploads, no tracking of what you type.</p><div class="row"><label class="sr-only" for="find">Find a tool</label><input id="find" type="search" placeholder="Search tools (try &quot;json&quot; or &quot;hash&quot;)" autocomplete="off" style="max-width:26rem"></div></section>${ad('top')}
<section id="tools"><h2>All tools</h2><div class="grid" id="tool-grid">${tools.map((t) => `<div data-find="${esc((t.title + ' ' + t.blurb).toLowerCase())}">${card(rel + t.slug + '/', t.emoji, t.title, t.blurb)}</div>`).join('')}<div data-find="http status codes reference 404 500 redirect">${card(rel + 'http-status-codes/', '📡', 'HTTP Status Codes', 'A searchable reference of every common HTTP status code and what it means.')}</div></div><p class="empty" id="no-match" hidden>No tool matches that search.</p></section>${ad('mid')}
<section class="prose full"><h2>Built for privacy</h2><p>Most online tools send your input to a server. DevPocket does the opposite: the code is downloaded once and everything runs on your device with standard browser features such as the Web Crypto API. That makes it quick, works on a flaky connection, and keeps API payloads, tokens and drafts private.</p><h2>Works on every screen</h2><p>Use it on a phone while debugging on the move, on a laptop, or on an ultra-wide monitor. Light and dark themes follow your system setting, and all tools work with the keyboard.</p></section>${ad('bottom')}` });
for (const t of tools) site.pages.push({ path: `${t.slug}/index.html`, title: t.title, desc: t.intro.slice(0, 155), nav: t.slug + '/', crumb: ['Tools', 'index.html#tools'], short: t.title, scripts: ['assets/tools.js', 'assets/tools-ui.js'], jsonld: faqLd(t.faq),
  body: ({ rel, ad }) => `<div data-tool="${t.id}"><h1>${esc(t.title)}</h1><p class="lead">${esc(t.intro)}</p>${ad('top')}${t.form}<noscript><p class="callout warn">This tool needs JavaScript. It runs entirely in your browser; nothing is uploaded.</p></noscript></div>
<article class="prose full">${t.about[0]}${ad('mid')}${t.about.slice(1).join('')}${faqHtml(t.faq)}</article><section><h2>More tools</h2><div class="grid">${t.related.map((r) => { const x = bySlug(r); return card(rel + x.slug + '/', x.emoji, x.title, x.blurb); }).join('')}</div></section>${ad('bottom')}` });
const cls = (c) => c < 200 ? '1xx' : c < 300 ? '2xx' : c < 400 ? '3xx' : c < 500 ? '4xx' : '5xx';
site.pages.push({ path: 'http-status-codes/index.html', title: 'HTTP Status Codes Reference', desc: 'Every common HTTP status code explained: 200, 301, 404, 500 and more, with plain-English meanings and when to use them.', nav: 'http-status-codes/', crumb: ['Tools', 'index.html#tools'], short: 'HTTP status codes', scripts: ['assets/status.js'],
  body: ({ ad }) => `<h1>HTTP Status Codes Reference</h1><p class="lead">Search or filter every common HTTP status code. Each response from a web server starts with a three-digit code that says what happened.</p>${ad('top')}
<div class="panel"><label for="sq">Search by code or word</label><input id="sq" type="search" placeholder="404, redirect, timeout..." autocomplete="off"><div class="chips" role="group" aria-label="Filter by class" style="margin-top:.6rem">${['1xx|1xx Info', '2xx|2xx Success', '3xx|3xx Redirect', '4xx|4xx Client error', '5xx|5xx Server error'].map((x) => { const [k, l] = x.split('|'); return `<button type="button" class="chip" data-cls="${k}" aria-pressed="false">${l}</button>`; }).join('')}</div></div>
<div class="table-wrap" style="margin-top:1rem"><table id="st"><thead><tr><th>Code</th><th>Name</th><th>Meaning</th></tr></thead><tbody>${status.map(([c, n, d]) => `<tr data-c="${cls(c)}" data-q="${esc((c + ' ' + n + ' ' + d).toLowerCase())}"><td><strong>${c}</strong></td><td>${esc(n)}</td><td>${esc(d)}</td></tr>`).join('')}</tbody></table></div><p class="empty" id="sn" hidden>No status code matches.</p>${ad('mid')}
<article class="prose full"><h2>The five classes</h2><ul><li><strong>1xx</strong> - informational: the request is still being processed.</li><li><strong>2xx</strong> - success: the request worked.</li><li><strong>3xx</strong> - redirection: look somewhere else.</li><li><strong>4xx</strong> - client error: the request has a problem (wrong URL, no permission, bad data).</li><li><strong>5xx</strong> - server error: the server failed on a valid request.</li></ul><h2>401 vs 403</h2><p>401 means "I do not know who you are - log in". 403 means "I know who you are and you may not do this". For a resource you want to hide completely, some sites deliberately return 404 instead of 403.</p><h2>301 vs 302 and SEO</h2><p>Use 301 (or 308) when a page has moved for good so search engines pass ranking to the new URL; use 302 (or 307) for temporary moves such as maintenance or A/B tests.</p><h2>Debugging tips</h2><ul><li>4xx: re-check the URL, method, headers, authentication and request body.</li><li>5xx: look at the server logs first; the client usually cannot fix it.</li><li>429: slow down and honour the Retry-After header; add exponential backoff.</li><li>502/504: the problem is between a proxy and the app behind it - check that the app is running and not timing out.</li></ul></article>${ad('bottom')}` });
module.exports = site;
